import {requirePage} from "@/shared/auth/account";
import {attendanceSecurityOverview} from "@/modules/attendance/infrastructure/security-repository";
import {organizationCatalogs} from "@/modules/organization/infrastructure/repository";
import {assetCatalog} from "@/modules/asset/infrastructure/repository";
import {dateInTimeZone} from "@/shared/domain/date-time";
import {environment} from "@/shared/infrastructure/env";
import {PageHeading} from "@/components/page-heading";
import {CommandForm} from "@/components/command-form";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Badge} from "@/components/ui/badge";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";
export const dynamic="force-dynamic";
const modes=[{value:"OFF",label:"OFF · 기존 로그인 방식"},{value:"DEVICE_ONLY",label:"등록 기기"},
 {value:"NETWORK_ONLY",label:"회사 네트워크"},{value:"DEVICE_AND_NETWORK",label:"등록 기기 + 회사 네트워크"},
 {value:"REMOTE_APPROVED",label:"승인된 재택·출장 + 등록 기기"}];
export default async function AttendanceVerificationPage(){
 const account=await requirePage("ATTENDANCE_VERIFICATION_READ");
 const today=dateInTimeZone(new Date(),environment().COMPANY_TIMEZONE);
 const [data,people,assets]=await Promise.all([attendanceSecurityOverview(today),organizationCatalogs(),assetCatalog()]);
 const canManage=account.permissions.includes("ATTENDANCE_VERIFICATION_MANAGE");
 const names=new Map(people.directory.map(person=>[person.id,person.name]));
 const assetCodes=new Map(assets.assets.map(asset=>[asset.id,asset.asset_code]));
 const devices=new Map(assets.devices.map(device=>[device.id,`${assetCodes.get(device.asset_id)??device.hostname} · ${device.hostname}`]));
 const verified=data.events.filter(event=>event.verification_status==="VERIFIED"&&["DEVICE_ONLY","NETWORK_ONLY","DEVICE_AND_NETWORK","REMOTE_APPROVED"].includes(event.verification_type)).length;
 const failed=data.verifications.filter(item=>item.status==="FAILED");
 return <><PageHeading eyebrow="ATTENDANCE TRUST" title="출퇴근 검증" description="등록 기기와 회사 네트워크 검증 결과를 확인하고 허용 정책을 관리합니다."/>
  <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["오늘 검증 출근",verified],["검증 실패",failed.length],["기기 문제",failed.filter(item=>item.device_status==="FAILED").length],["네트워크 문제",failed.filter(item=>item.network_status==="FAILED"||item.network_status==="UNKNOWN").length]].map(([label,value])=><Card key={label} className="gap-0 py-4"><CardContent><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></CardContent></Card>)}</div>
  {canManage&&<div className="mb-5 grid gap-5 xl:grid-cols-2"><Card><CardHeader><CardTitle>출퇴근 검증 정책</CardTitle></CardHeader><CardContent><p className="mb-4 text-xs text-muted-foreground">현재 설정: {modes.find(mode=>mode.value===data.setting.mode)?.label??data.setting.mode}. 허용 네트워크가 없으면 네트워크 검증은 통과하지 않습니다.</p><CommandForm endpoint="/api/attendance-security" action="policy.save" constants={{version:data.setting.version}} fields={[{name:"mode",label:"검증 방식",type:"select",required:true,value:data.setting.mode,options:modes}]} submit="검증 정책 저장"/></CardContent></Card>
  <Card><CardHeader><CardTitle>회사 네트워크</CardTitle></CardHeader><CardContent className="space-y-3">{data.networks.map(network=><details key={network.id} className="rounded-md border p-3 text-xs"><summary className="cursor-pointer font-semibold">{network.name} · {network.cidr} · {network.active?"사용":"중지"}</summary><div className="mt-4"><CommandForm endpoint="/api/attendance-security" action="network.save" constants={{id:network.id,version:network.version}} fields={[{name:"name",label:"이름",value:network.name,required:true},{name:"cidr",label:"CIDR",value:network.cidr,required:true},{name:"active",label:"사용",type:"checkbox",value:network.active}]} submit="네트워크 수정"/></div></details>)}<CommandForm endpoint="/api/attendance-security" action="network.save" fields={[{name:"name",label:"새 네트워크 이름",required:true},{name:"cidr",label:"CIDR (예: 203.0.113.10/32)",required:true},{name:"active",label:"사용",type:"checkbox",value:true}]} submit="네트워크 추가"/></CardContent></Card></div>}
  {canManage&&<Card className="mb-5"><CardHeader><CardTitle>재택·출장·외근 예외</CardTitle></CardHeader><CardContent><p className="mb-4 text-xs text-muted-foreground">관리자가 사유와 기간을 남겨 승인합니다. 예외 중에도 등록 회사 PC 검증은 필요합니다.</p><div className="mb-5 space-y-2">{data.exceptions.map(item=><details key={item.id} className="rounded-md border p-3 text-xs"><summary className="cursor-pointer">{names.get(item.user_id)??"직원"} · {item.kind} · {item.starts_on} ~ {item.ends_on} · {item.active?"승인":"중지"}</summary><div className="mt-4"><CommandForm endpoint="/api/attendance-security" action="remote.save" constants={{id:item.id,version:item.version,user_id:item.user_id}} fields={[{name:"kind",label:"유형",type:"select",value:item.kind,required:true,options:[{value:"REMOTE",label:"재택"},{value:"BUSINESS_TRIP",label:"출장"},{value:"OFFSITE",label:"외근"}]},{name:"starts_on",label:"시작일",type:"date",value:item.starts_on,required:true},{name:"ends_on",label:"종료일",type:"date",value:item.ends_on,required:true},{name:"reason",label:"승인 사유",value:item.reason,required:true},{name:"approval_reference",label:"승인 참조",value:item.approval_reference??""},{name:"active",label:"사용",type:"checkbox",value:item.active}]} submit="예외 변경"/></div></details>)}</div><CommandForm endpoint="/api/attendance-security" action="remote.save" fields={[{name:"user_id",label:"직원",type:"select",required:true,options:people.directory.map(person=>({value:person.id,label:person.name}))},{name:"kind",label:"유형",type:"select",required:true,options:[{value:"REMOTE",label:"재택"},{value:"BUSINESS_TRIP",label:"출장"},{value:"OFFSITE",label:"외근"}]},{name:"starts_on",label:"시작일",type:"date",required:true},{name:"ends_on",label:"종료일",type:"date",required:true},{name:"reason",label:"승인 사유",required:true},{name:"approval_reference",label:"승인 참조"},{name:"active",label:"사용",type:"checkbox",value:true}]} submit="예외 승인"/></CardContent></Card>}
  <Card><CardHeader><CardTitle>오늘 검증 시도</CardTitle></CardHeader><CardContent className="overflow-x-auto"><Table><TableHeader><TableRow>{["시간","직원","유형","기기","네트워크","결과","사유"].map(label=><TableHead key={label}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{data.verifications.map(item=><TableRow key={item.id}><TableCell>{new Date(item.created_at).toLocaleTimeString("ko-KR",{timeZone:"Asia/Seoul"})}</TableCell><TableCell>{names.get(item.user_id)??"직원"}</TableCell><TableCell>{item.mode}</TableCell><TableCell>{item.device_id?devices.get(item.device_id)??"등록 기기":item.device_status}</TableCell><TableCell>{item.network_status}</TableCell><TableCell><Badge variant="outline">{item.status}</Badge></TableCell><TableCell>{item.reason_code??"—"}</TableCell></TableRow>)}</TableBody></Table>{!data.verifications.length&&<p className="p-5 text-xs text-muted-foreground">오늘 검증 시도가 없습니다.</p>}</CardContent></Card>
 </>;
}
