import Link from "next/link";
import {requireAnyPage} from "@/shared/auth/account";
import {organizationCatalogs} from "@/modules/organization/infrastructure/repository";
import {skillCatalog,skillMatrix} from "@/modules/workforce-profile/infrastructure/repository";
import {PageHeading} from "@/components/page-heading";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Badge} from "@/components/ui/badge";
import {CommandForm} from "@/components/command-form";
import {Input} from "@/components/ui/input";
import {Button} from "@/components/ui/button";
import {dateInTimeZone} from "@/shared/domain/date-time";
import {environment} from "@/shared/infrastructure/env";
import {addDays,dateNumber} from "@/modules/project-resource/domain/metrics";
export default async function WorkforceMatrixPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const account=await requireAnyPage(["WORKFORCE_PROFILE_READ_TEAM","WORKFORCE_PROFILE_READ_ALL"]);const query=await searchParams;
 const today=dateInTimeZone(new Date(),environment().COMPANY_TIMEZONE);const valid=(value?:string)=>!!value&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(dateNumber(value));
 const start=valid(query.start)?query.start!:today,end=valid(query.end)&&dateNumber(query.end!)>=dateNumber(start)&&dateNumber(query.end!)-dateNumber(start)<=185?query.end!:addDays(start,60);
 const [catalogs,skills]=await Promise.all([organizationCatalogs(),skillCatalog()]);
 const org=catalogs.organizations.some(x=>x.id===query.organization)?query.organization:undefined,pos=catalogs.positions.some(x=>x.id===query.position)?query.position:undefined,skill=skills.some(x=>x.id===query.skill)?query.skill:undefined;
 const months=Math.min(720,Math.max(0,Number(query.career)||0)),availability=Math.min(100,Math.max(0,Number(query.availability)||0));
 const rows=await skillMatrix({start,end,organizationId:org,positionId:pos,skillId:skill,minCareerMonths:months,minAvailability:availability});
 const visibleSkills=skill?skills.filter(s=>s.id===skill):skills.filter(s=>rows.some(r=>r.skills.some(x=>x.id===s.id))).slice(0,24);
 return <><PageHeading eyebrow="WORKFORCE SKILLS" title="인력 기술 현황" description="관리 조직의 기술과 기간별 가용률을 확인합니다. 기술 수준은 인사 평가 점수가 아닙니다."/>
 <Card className="mb-5"><CardHeader><CardTitle>검색 조건</CardTitle></CardHeader><CardContent><form className="grid items-end gap-3 text-sm sm:grid-cols-3 xl:grid-cols-7"><label className="block space-y-2"><span className="text-xs">시작일</span><Input name="start" type="date" defaultValue={start}/></label><label className="block space-y-2"><span className="text-xs">종료일</span><Input name="end" type="date" defaultValue={end}/></label><label className="block space-y-2"><span className="text-xs">조직</span><select name="organization" defaultValue={org??""}><option value="">전체</option>{catalogs.organizations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="block space-y-2"><span className="text-xs">직급</span><select name="position" defaultValue={pos??""}><option value="">전체</option>{catalogs.positions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="block space-y-2"><span className="text-xs">기술</span><select name="skill" defaultValue={skill??""}><option value="">전체</option>{skills.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="block space-y-2"><span className="text-xs">최소 경력 (개월)</span><Input name="career" type="number" min="0" max="720" defaultValue={months}/></label><label className="block space-y-2"><span className="text-xs">최소 가용률 (%)</span><Input name="availability" type="number" min="0" max="100" defaultValue={availability}/></label><Button type="submit" className="sm:col-span-3 xl:col-span-1">검색</Button></form></CardContent></Card>
 <Card><CardHeader><CardTitle>Skill Matrix · {rows.length}명</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b text-left"><th className="p-2">직원</th><th className="p-2">조직 / 경력</th><th className="p-2">최저 가용률</th>{visibleSkills.map(s=><th key={s.id} className="p-2 text-center">{s.name}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.user_id} className="border-b"><td className="p-2 font-medium"><Link className="text-primary hover:underline" href={`/workforce-profiles/${r.user_id}`}>{r.name}</Link></td><td className="p-2">{catalogs.organizations.find(x=>x.id===r.organization_id)?.name??"—"} · {r.career_months??"—"}개월</td><td className="p-2"><Badge variant="outline">{r.minimum_availability}%</Badge></td>{visibleSkills.map(s=><td className="p-2 text-center" key={s.id}>{r.skills.some(x=>x.id===s.id)?"●":""}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="py-8 text-center text-xs text-muted-foreground">조건에 맞는 직원이 없습니다.</p>}</CardContent></Card>
 {account.permissions.includes("WORKFORCE_PROFILE_MANAGE")&&<Card className="mt-5"><CardHeader><CardTitle>기술 카탈로그 관리</CardTitle></CardHeader><CardContent><details><summary className="cursor-pointer text-sm">기술 추가</summary><div className="mt-4"><CommandForm endpoint="/api/workforce-profile" action="skill_catalog.save" fields={[{name:"code",label:"코드 (영문/숫자/밑줄)",required:true},{name:"name",label:"기술명",required:true},{name:"category",label:"분류",value:"ETC",required:true},{name:"active",label:"사용",type:"checkbox",value:true}]}/></div></details><div className="mt-4 grid gap-2 sm:grid-cols-3">{skills.map(s=><details key={s.id} className="rounded border p-2 text-xs"><summary className="cursor-pointer">{s.name} · {s.category}</summary><div className="mt-3"><CommandForm key={s.version} endpoint="/api/workforce-profile" action="skill_catalog.save" constants={{id:s.id,version:s.version}} fields={[{name:"code",label:"코드",value:s.code,required:true},{name:"name",label:"기술명",value:s.name,required:true},{name:"category",label:"분류",value:s.category,required:true},{name:"active",label:"사용",type:"checkbox",value:s.active}]}/></div></details>)}</div></CardContent></Card>}
 </>;
}
