import { BriefcaseBusiness, CalendarClock, Gauge } from "lucide-react";
import { requirePage } from "@/shared/auth/account";
import { projectCatalog } from "@/modules/project/infrastructure/repository";
import { assignmentStatusLabels,projectStatusLabels } from "@/modules/project/domain/contracts";
import { PageHeading } from "@/components/page-heading";
import { Card,CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table";

export default async function MyProjectsPage(){const account=await requirePage("PROJECT_READ_SELF");const data=await projectCatalog();const projects=new Map(data.projects.map(project=>[project.id,project]));const assignments=data.assignments.filter(row=>row.user_id===account.id);const current=assignments.filter(row=>row.status==="IN_PROGRESS");const allocation=current.reduce((sum,row)=>sum+row.allocation_rate,0);return <>
  <PageHeading eyebrow="MY PROJECTS" title="내 프로젝트" description="현재와 예정 프로젝트의 투입 기간, 역할, 투입률을 확인합니다."/>
  <div className="mb-6 grid gap-4 sm:grid-cols-3"><Card><CardContent><BriefcaseBusiness size={20} className="mb-4 text-primary"/><p className="text-xs text-muted-foreground">현재 프로젝트</p><p className="mt-2 text-2xl font-bold">{current.length}<span className="ml-1 text-xs font-normal">개</span></p></CardContent></Card><Card><CardContent><Gauge size={20} className="mb-4 text-primary"/><p className="text-xs text-muted-foreground">현재 투입률</p><p className="mt-2 text-2xl font-bold">{allocation}<span className="ml-1 text-xs font-normal">%</span></p></CardContent></Card><Card><CardContent><CalendarClock size={20} className="mb-4 text-primary"/><p className="text-xs text-muted-foreground">예정 투입</p><p className="mt-2 text-2xl font-bold">{assignments.filter(row=>["PLANNED","CONFIRMED"].includes(row.status)).length}<span className="ml-1 text-xs font-normal">건</span></p></CardContent></Card></div>
  <Card className="gap-0 py-0"><CardContent className="px-0"><Table><TableHeader><TableRow><TableHead className="pl-5">프로젝트</TableHead><TableHead>고객사</TableHead><TableHead>역할</TableHead><TableHead>투입기간</TableHead><TableHead>투입률</TableHead><TableHead>상태</TableHead></TableRow></TableHeader><TableBody>{assignments.map(row=>{const project=projects.get(row.project_id);return <TableRow key={row.id}><TableCell className="pl-5 font-semibold">{project?.project_name??"—"}<p className="mt-1 text-[10px] font-normal text-muted-foreground">{project?.project_code}</p></TableCell><TableCell>{project?.customer_name??"—"}</TableCell><TableCell>{row.project_role}</TableCell><TableCell>{row.planned_start_date} – {row.planned_end_date}</TableCell><TableCell>{row.allocation_rate}%</TableCell><TableCell><Badge variant="outline">{assignmentStatusLabels[row.status as keyof typeof assignmentStatusLabels]??projectStatusLabels[project?.status as keyof typeof projectStatusLabels]}</Badge></TableCell></TableRow>})}</TableBody></Table>{!assignments.length?<p className="py-16 text-center text-xs text-muted-foreground">프로젝트 투입 이력이 없습니다.</p>:null}</CardContent></Card>
</>}
