import "server-only";
import {z} from "zod";
import {serverClient} from "@/shared/infrastructure/supabase/server";
import {databaseError} from "@/shared/domain/errors";
import type {WorkManagementRepository} from "../application/commands";
export const workLogSchema=z.object({id:z.uuid(),user_id:z.uuid(),work_date:z.string(),work_category:z.string(),project_id:z.uuid().nullable(),project_task_id:z.uuid().nullable(),title:z.string(),description:z.string(),start_time:z.string().nullable(),end_time:z.string().nullable(),work_minutes:z.number(),progress:z.number().nullable(),status:z.string(),blocker:z.string().nullable(),memo:z.string().nullable(),version:z.number(),created_at:z.string(),updated_at:z.string()});
export const weeklyReportSchema=z.object({id:z.uuid(),user_id:z.uuid(),week_start_date:z.string(),week_end_date:z.string(),summary:z.string(),completed_work:z.string(),in_progress_work:z.string(),issues:z.string(),next_week_plan:z.string(),entries_snapshot:z.array(z.object({id:z.uuid(),date:z.string(),category:z.string(),project_id:z.uuid().nullable(),project_name:z.string().nullable(),title:z.string(),description:z.string(),minutes:z.number(),status:z.string(),blocker:z.string().nullable()})),status:z.string(),snapshot_taken_at:z.string(),confirmed_at:z.string().nullable(),version:z.number(),created_at:z.string(),updated_at:z.string()});
export const rosterSchema=z.object({user_id:z.uuid(),name:z.string(),organization_id:z.uuid().nullable(),report_id:z.uuid().nullable(),status:z.string().nullable(),approved_leave_days:z.number()});
export function workManagementRepository():WorkManagementRepository{return {async execute(command,requestId){const client=await serverClient();const {data,error}=await client.rpc("work_management_command",{p_action:command.action,p_payload:command.payload,p_request_id:requestId});if(error)throw databaseError(error);return data}}}
export async function workLogs(start:string,end:string,userId?:string){const client=await serverClient();let query=client.from("daily_work_logs").select("*").gte("work_date",start).lte("work_date",end).order("work_date",{ascending:false}).order("start_time").limit(1000);if(userId)query=query.eq("user_id",userId);const {data,error}=await query;if(error)throw databaseError(error);return workLogSchema.array().parse(data)}
export async function projectWorkLogs(projectId:string,start:string,end:string){const client=await serverClient();const {data,error}=await client.from("daily_work_logs").select("*").eq("project_id",projectId).gte("work_date",start).lte("work_date",end).order("work_date",{ascending:false}).limit(500);if(error)throw databaseError(error);return workLogSchema.array().parse(data)}
export async function weeklyReport(weekStart:string,userId:string){const client=await serverClient();const {data,error}=await client.from("weekly_reports").select("*").eq("week_start_date",weekStart).eq("user_id",userId).maybeSingle();if(error)throw databaseError(error);return data?weeklyReportSchema.parse(data):null}
export async function weeklyReports(weekStart:string){const client=await serverClient();const {data,error}=await client.from("weekly_reports").select("*").eq("week_start_date",weekStart).order("user_id").limit(1000);if(error)throw databaseError(error);return weeklyReportSchema.array().parse(data)}
export async function weeklyRoster(weekStart:string){const client=await serverClient();const {data,error}=await client.rpc("weekly_report_roster",{p_week_start:weekStart});if(error)throw databaseError(error);return rosterSchema.array().parse(data)}
export const dailyStatusSchema=z.object({user_id:z.uuid(),name:z.string(),organization_id:z.uuid().nullable(),entry_count:z.number(),total_minutes:z.number()});
export async function workDailyStatus(date:string){const client=await serverClient();const {data,error}=await client.rpc("work_log_daily_status",{p_date:date});if(error)throw databaseError(error);return dailyStatusSchema.array().parse(data)}
