import {afterAll,beforeAll,describe,expect,it} from "vitest";
import {loadEnvFile} from "node:process";
import postgres from "postgres";
import {createClient,type SupabaseClient} from "@supabase/supabase-js";
loadEnvFile(".env.local");
const apiUrl=process.env.NEXT_PUBLIC_SUPABASE_URL!;const dbUrl=process.env.TEST_DATABASE_URL!;
if(!["127.0.0.1","localhost"].includes(new URL(apiUrl).hostname)||!["127.0.0.1","localhost"].includes(new URL(dbUrl).hostname))throw new Error("Local disposable database required");
const sql=postgres(dbUrl,{max:1});const makeClient=()=>createClient(apiUrl,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}});
let employee:SupabaseClient,manager:SupabaseClient,admin:SupabaseClient,employeeId:string,adminId:string,logId:string,reportId:string;
const week="2026-09-21";
const run=(client:SupabaseClient,action:string,payload:Record<string,unknown>)=>client.rpc("work_management_command",{p_action:action,p_payload:payload,p_request_id:crypto.randomUUID()});
const logPayload={work_date:week,work_category:"INTERNAL_DEVELOPMENT",project_id:"",project_task_id:"",title:"Phase 7 integration",description:"",start_time:"09:00",end_time:"10:00",work_minutes:60,progress:"",status:"DONE",blocker:"",memo:""};
beforeAll(async()=>{employee=makeClient();manager=makeClient();admin=makeClient();for(const [client,name] of [[employee,"employee"],[manager,"manager"],[admin,"admin"]] as const){const {error}=await client.auth.signInWithPassword({email:`${name}@digitalsquare.local`,password:process.env.SEED_PASSWORD!});if(error)throw error}employeeId=(await employee.auth.getUser()).data.user!.id;adminId=(await admin.auth.getUser()).data.user!.id});
afterAll(async()=>{if(reportId){await sql`delete from public.audit_logs where entity_id=${reportId}`;await sql`delete from public.weekly_reports where id=${reportId}`}if(logId){await sql`delete from public.audit_logs where entity_id=${logId}`;await sql`delete from public.daily_work_logs where id=${logId}`}await sql.end()});
describe("Phase 7 employee work and weekly snapshot",()=>{
 it("allows a projectless log, blocks another employee mutation, and respects team scope",async()=>{const created=await run(employee,"work_log.save",logPayload);expect(created.error).toBeNull();logId=created.data.id;expect((await employee.from("daily_work_logs").select("id,project_id").eq("id",logId)).data).toEqual([{id:logId,project_id:null}]);expect((await manager.from("daily_work_logs").select("id").eq("id",logId)).data).toHaveLength(1);expect((await manager.from("daily_work_logs").select("id").eq("user_id",adminId)).data).toEqual([]);const forbidden=await run(manager,"work_log.save",{...logPayload,id:logId,version:1,title:"Changed"});expect(forbidden.error?.code).toBe("42501");expect((await employee.from("daily_work_logs").update({title:"Direct"}).eq("id",logId)).error?.code).toBe("42501")});
 it("links to an existing project while preserving the optional relationship",async()=>{const updated=await run(employee,"work_log.save",{...logPayload,id:logId,version:1,work_category:"PROJECT",project_id:"50000000-0000-4000-8000-000000000001",title:"Project work"});expect(updated.error).toBeNull();const [row]=await sql`select project_id,version from public.daily_work_logs where id=${logId}`;expect(row.project_id).toBe("50000000-0000-4000-8000-000000000001");expect(row.version).toBe(2);expect((await run(employee,"work_log.save",{...logPayload,id:logId,version:1})).error?.code).toBe("40001")});
 it("includes projectless active employees and freezes a confirmed report",async()=>{const roster=await employee.rpc("weekly_report_roster",{p_week_start:week});expect(roster.error).toBeNull();expect(roster.data.some((person:{user_id:string})=>person.user_id===employeeId)).toBe(true);const generated=await run(employee,"weekly_report.generate",{week_start_date:week});expect(generated.error).toBeNull();reportId=generated.data.id;let [report]=await sql`select * from public.weekly_reports where id=${reportId}`;expect(report.entries_snapshot).toHaveLength(1);expect(report.entries_snapshot[0].project_name).toBeTruthy();const saved=await run(employee,"weekly_report.save",{week_start_date:week,version:report.version,summary:"한 주 요약",completed_work:"완료",in_progress_work:"진행",issues:"",next_week_plan:"다음 주 계획"});expect(saved.error).toBeNull();[report]=await sql`select * from public.weekly_reports where id=${reportId}`;expect((await run(employee,"weekly_report.confirm",{week_start_date:week,version:report.version})).error).toBeNull();const before=(await sql`select entries_snapshot,summary from public.weekly_reports where id=${reportId}`)[0];const log=(await sql`select version from public.daily_work_logs where id=${logId}`)[0];expect((await run(employee,"work_log.save",{...logPayload,id:logId,version:log.version,title:"Later edit"})).error).toBeNull();const after=(await sql`select entries_snapshot,summary from public.weekly_reports where id=${reportId}`)[0];expect(after).toEqual(before);expect((await run(employee,"weekly_report.refresh",{week_start_date:week,version:report.version+1})).error?.code).toBe("40001");expect((await manager.from("weekly_reports").select("id").eq("id",reportId)).data).toHaveLength(1)})
});
