import ExcelJS from "exceljs";
import type {SettlementExport} from "../domain/settlement";
import {expenseCategoryLabels} from "../domain/contracts";
const safe=(value:string)=>/^[=+\-@\t\r]/.test(value)?`'${value}`:value;
export async function buildSettlementExcel(report:SettlementExport){const workbook=new ExcelJS.Workbook();workbook.creator="Digital Square ERP";workbook.created=new Date(report.generated_at);const sheet=workbook.addWorksheet("법인카드 사용내역",{views:[{state:"frozen",ySplit:4}]});
 sheet.mergeCells("A1:L1");sheet.getCell("A1").value=`Digital Square 법인카드 정산 · ${report.settlement_month.slice(0,7)}`;sheet.getCell("A1").font={bold:true,size:16,color:{argb:"FF071C35"}};
 sheet.mergeCells("A2:L2");sheet.getCell("A2").value=`총 ${report.total_count}건  |  공급가액 ${report.total_supply_amount.toLocaleString("ko-KR")}  |  VAT ${report.total_vat_amount.toLocaleString("ko-KR")}  |  합계 ${report.total_amount.toLocaleString("ko-KR")}`;
 sheet.columns=[{key:"date",width:15},{key:"projectCode",width:19},{key:"projectName",width:29},{key:"card",width:29},{key:"user",width:17},{key:"merchant",width:25},{key:"purpose",width:36},{key:"category",width:16},{key:"supply",width:18},{key:"vat",width:18},{key:"total",width:18},{key:"memo",width:32}];
 const header=sheet.getRow(4);["사용일자","프로젝트 코드","프로젝트명","법인카드","사용자","거래처","사용 목적","비용 구분","공급가액","VAT","총 금액","비고"].forEach((label,index)=>header.getCell(index+1).value=label);header.font={bold:true,color:{argb:"FFFFFFFF"}};header.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF071C35"}};header.height=24;
 for(const item of report.entries_snapshot){const row=sheet.addRow({date:item.transaction_date,projectCode:safe(item.project_code),projectName:safe(item.project_name),card:safe(item.card),user:safe(item.user_name),merchant:safe(item.merchant),purpose:safe(item.purpose),category:expenseCategoryLabels[item.category as keyof typeof expenseCategoryLabels]??item.category,supply:item.supply_amount,vat:item.vat_amount,total:item.total_amount,memo:safe(item.memo)});for(const column of [9,10,11])row.getCell(column).numFmt='#,##0.00;[Red]-#,##0.00';if(row.number%2===0)row.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FFF6F8FB"}}}
 const total=sheet.addRow({purpose:"합계",supply:report.total_supply_amount,vat:report.total_vat_amount,total:report.total_amount});total.font={bold:true};for(const column of [9,10,11])total.getCell(column).numFmt='#,##0.00;[Red]-#,##0.00';sheet.autoFilter={from:"A4",to:"L4"};return Buffer.from(await workbook.xlsx.writeBuffer())}
