import {NextResponse} from "next/server";
import {z} from "zod";
import {currentAccount} from "@/shared/auth/account";
import {authorizeAny} from "@/modules/rbac/domain/policy";
import {serverClient} from "@/shared/infrastructure/supabase/server";
import {databaseError} from "@/shared/domain/errors";
import {failure} from "@/shared/infrastructure/http";
const types:Record<string,string>={"image/jpeg":"jpg","image/png":"png","image/webp":"webp","application/pdf":"pdf"};
export async function POST(request:Request){const requestId=crypto.randomUUID();try{authorizeAny(await currentAccount(),["EXPENSE_WRITE_SELF","EXPENSE_MANAGE"]);const form=await request.formData();const id=z.uuid().parse(form.get("expense_id"));const version=z.coerce.number().int().positive().parse(form.get("version"));const file=form.get("file");if(!(file instanceof File)||!types[file.type]||file.size<=0||file.size>10*1024*1024)throw new Error("10MB 이하의 JPEG, PNG, WebP 또는 PDF만 업로드할 수 있습니다.");const client=await serverClient();const key=`${id}/${crypto.randomUUID()}.${types[file.type]}`;const uploaded=await client.storage.from("expense-receipts").upload(key,Buffer.from(await file.arrayBuffer()),{contentType:file.type,upsert:false});if(uploaded.error)throw uploaded.error;const saved=await client.rpc("corporate_card_command",{p_action:"expense.receipt",p_payload:{id,version,receipt_key:key},p_request_id:requestId});if(saved.error){await client.storage.from("expense-receipts").remove([key]);throw databaseError(saved.error)}return NextResponse.json({data:{message:"영수증을 저장했습니다."}},{headers:{"Cache-Control":"no-store"}})}catch(error){return failure(error,requestId)}}
export async function GET(request:Request){const requestId=crypto.randomUUID();try{authorizeAny(await currentAccount(),["EXPENSE_READ_SELF","EXPENSE_READ_PROJECT","EXPENSE_READ_ALL"]);const id=z.uuid().parse(new URL(request.url).searchParams.get("id"));const client=await serverClient();const row=await client.from("expenses").select("receipt_key").eq("id",id).single();if(row.error)throw databaseError(row.error);if(!row.data.receipt_key)throw new Error("영수증이 없습니다.");const result=await client.storage.from("expense-receipts").download(row.data.receipt_key);if(result.error)throw result.error;return new NextResponse(result.data.stream(),{headers:{"Content-Type":result.data.type||"application/octet-stream","Content-Disposition":"inline","Cache-Control":"private, no-store","X-Content-Type-Options":"nosniff"}})}catch(error){return failure(error,requestId)}}
