"use client";
import {useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Button} from "@/components/ui/button";
import {Badge} from "@/components/ui/badge";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";
import {expenseCategoryLabels} from "@/modules/corporate-card/domain/contracts";
import type {z} from "zod";
import type {settlementSchema,deliverySchema,settingSchema} from "@/modules/corporate-card/infrastructure/repository";
type Report=z.infer<typeof settlementSchema>;type Delivery=z.infer<typeof deliverySchema>;type Setting=z.infer<typeof settingSchema>;
const money=(value:number)=>`${value.toLocaleString("ko-KR")}원`;
export function CardSettlementClient({month,reports,report,deliveries,setting,canManage,canSend,canReopen}:{month:string;reports:Report[];report:Report|null;deliveries:Delivery[];setting:Setting|null;canManage:boolean;canSend:boolean;canReopen:boolean}){const router=useRouter();const [busy,setBusy]=useState(false),[message,setMessage]=useState(""),[testEmail,setTestEmail]=useState("");const [config,setConfig]=useState({enabled:setting?.value.enabled??false,recipients:setting?.value.recipients.join(", ")??"",cc:setting?.value.cc.join(", ")??"",send_day:setting?.value.send_day??1,send_time:setting?.value.send_time??"09:00",subject_template:setting?.value.subject_template??"Digital Square 법인카드 {month} 정산"});
 async function submit(path:string,body:unknown){setBusy(true);setMessage("");try{const response=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error?.message??"처리하지 못했습니다.");setMessage(result.data?.message??"처리했습니다.");router.refresh()}catch(error){setMessage(error instanceof Error?error.message:"연결을 확인해 주세요.")}finally{setBusy(false)}}
 const command=(action:string,payload:Record<string,unknown>)=>submit("/api/corporate-card",{action,payload});const base={settlement_month:month,...report&&{version:report.version}};
 const labels:Record<string,string>={DRAFT:"초안",REVIEW:"검토",CLOSED:"마감",SENT:"발송 완료"};
 return <div className="space-y-5"><div className="flex flex-wrap items-center gap-3"><label className="text-xs font-semibold" htmlFor="settlement-month">기준월</label><input id="settlement-month" type="month" value={month.slice(0,7)} onChange={event=>router.push(`/admin/card-settlements?month=${event.target.value}-01`)} className="w-44 rounded-md border bg-white px-3 py-2 text-sm"/><span className="text-xs text-muted-foreground">월 정산은 전월 카드 사용내역을 기준으로 합니다.</span></div>
 <div className="grid gap-5 xl:grid-cols-[1fr_2fr]"><Card><CardHeader><CardTitle>정산 이력</CardTitle></CardHeader><CardContent className="space-y-2">{reports.map(item=><Link key={item.id} href={`/admin/card-settlements?month=${item.settlement_month}`} className={`flex items-center justify-between rounded-md border px-3 py-2 text-xs ${month===item.settlement_month?"border-primary bg-brand-soft":""}`}><span>{item.settlement_month.slice(0,7)} · {money(item.total_amount)}</span><Badge variant="outline">{labels[item.status]??item.status}</Badge></Link>)}{!reports.length&&<p className="text-xs text-muted-foreground">아직 정산 이력이 없습니다.</p>}</CardContent></Card><Card><CardHeader><CardTitle>{month.slice(0,7)} 정산 {report&&<Badge variant="outline">{labels[report.status]??report.status}</Badge>}</CardTitle></CardHeader><CardContent>{report?<><div className="mb-5 grid grid-cols-2 gap-3 text-xs sm:grid-cols-4">{[["사용 건수",`${report.total_count}건`],["공급가액",money(report.total_supply_amount)],["VAT",money(report.total_vat_amount)],["총액",money(report.total_amount)]].map(([label,value])=><div key={label} className="rounded-md border bg-muted/30 p-3"><p className="text-muted-foreground">{label}</p><p className="mt-2 font-semibold">{value}</p></div>)}</div><p className="mb-4 text-xs text-muted-foreground">생성 {report.generated_at.slice(0,16).replace("T"," ")} · 발송 {report.sent_at?.slice(0,16).replace("T"," ")??"—"} · 파일 SHA-256 {report.checksum?.slice(0,16)??"—"}</p></>:<p className="mb-5 text-xs text-muted-foreground">이 기준월의 정산 보고서가 없습니다.</p>}
 <div className="flex flex-wrap gap-2">{canManage&&(!report||["DRAFT","REVIEW"].includes(report.status))&&<Button disabled={busy} size="sm" onClick={()=>void command("settlement.generate",base)}>{report?"정산 다시 집계":"정산 생성"}</Button>}{canManage&&report&&["DRAFT","REVIEW"].includes(report.status)&&<Button disabled={busy} size="sm" variant="outline" onClick={()=>void submit("/api/corporate-card/settlement-file",{settlement_month:month,version:report.version})}>Excel 미리 생성</Button>}{report?.file_key&&<a className="rounded-md border px-3 py-2 text-xs" href={`/api/corporate-card/settlement-file?month=${month}`}>Excel 다운로드</a>}{canManage&&report?.status==="DRAFT"&&<Button disabled={busy} size="sm" variant="outline" onClick={()=>void command("settlement.transition",{...base,status:"REVIEW"})}>검토로 이동</Button>}{canManage&&report?.status==="REVIEW"&&<Button disabled={busy||!report.file_key} size="sm" variant="outline" onClick={()=>void command("settlement.transition",{...base,status:"CLOSED"})}>월 마감</Button>}{canSend&&report?.status==="CLOSED"&&<Button disabled={busy} size="sm" onClick={()=>void command("settlement.queue",{...base,force:true})}>정산 메일 발송</Button>}{canSend&&report?.status==="SENT"&&<Button disabled={busy} size="sm" variant="outline" onClick={()=>{if(confirm("정산 메일을 다시 발송하시겠습니까?"))void command("settlement.queue",{...base,force:true,resend:true})}}>재발송</Button>}{canReopen&&report&&["CLOSED","SENT"].includes(report.status)&&<Button disabled={busy} size="sm" variant="outline" onClick={()=>{if(confirm("마감을 재개방하면 기존 Excel 파일은 무효화됩니다. 계속하시겠습니까?"))void command("settlement.transition",{...base,status:"DRAFT"})}}>관리자 재개방</Button>}</div>
 {report?.file_key&&canSend&&<div className="mt-5 flex items-end gap-2 border-t pt-4"><label className="text-xs">테스트 수신 주소<input type="email" value={testEmail} onChange={event=>setTestEmail(event.target.value)} className="mt-1 block w-64 rounded-md border px-3 py-2 text-sm"/></label><Button size="sm" variant="outline" disabled={busy||!testEmail} onClick={()=>void submit("/api/corporate-card/test-email",{report_id:report.id,email:testEmail})}>테스트 메일</Button></div>}{message&&<p role="status" className="mt-4 text-xs text-primary">{message}</p>}</CardContent></Card></div>
 {report&&<Card><CardHeader><CardTitle>정산 내역 스냅샷</CardTitle></CardHeader><CardContent className="overflow-x-auto"><Table><TableHeader><TableRow>{["사용일자","프로젝트","카드","사용자","거래처","목적","구분","공급가액","VAT","합계"].map(label=><TableHead key={label}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{report.entries_snapshot.map(item=><TableRow key={item.id}><TableCell>{item.transaction_date}</TableCell><TableCell>{item.project_code}<p className="text-[11px] text-muted-foreground">{item.project_name}</p></TableCell><TableCell>{item.card}</TableCell><TableCell>{item.user_name}</TableCell><TableCell>{item.merchant}</TableCell><TableCell>{item.purpose}</TableCell><TableCell>{expenseCategoryLabels[item.category as keyof typeof expenseCategoryLabels]??item.category}</TableCell><TableCell>{money(item.supply_amount)}</TableCell><TableCell>{money(item.vat_amount)}</TableCell><TableCell>{money(item.total_amount)}</TableCell></TableRow>)}</TableBody></Table>{!report.entries_snapshot.length&&<p className="p-5 text-xs text-muted-foreground">해당 월 비용 내역이 없습니다.</p>}</CardContent></Card>}
 {report&&<Card><CardHeader><CardTitle>발송 이력</CardTitle></CardHeader><CardContent className="space-y-2">{deliveries.map(item=><div key={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded-md border p-3 text-xs"><span>{item.recipient_email}</span><span>{item.status} · 시도 {item.attempt_count}회 · {item.recent_attempt?.attempted_at.slice(0,16).replace("T"," ")??"—"}</span><span className="text-destructive">{item.last_error_code??item.recent_attempt?.error_code??""}</span></div>)}{!deliveries.length&&<p className="text-xs text-muted-foreground">발송 이력이 없습니다.</p>}</CardContent></Card>}
 {canManage&&setting&&<Card><CardHeader><CardTitle>자동 발송 설정</CardTitle></CardHeader><CardContent><form className="grid gap-4 sm:grid-cols-2" onSubmit={event=>{event.preventDefault();void command("settlement.setting",{version:setting.version,enabled:config.enabled,recipients:config.recipients.split(/[;,\n]/).map(value=>value.trim()).filter(Boolean),cc:config.cc.split(/[;,\n]/).map(value=>value.trim()).filter(Boolean),send_day:Number(config.send_day),send_time:config.send_time,timezone:"Asia/Seoul",subject_template:config.subject_template})}}><label className="text-xs">자동 발송 <input type="checkbox" checked={config.enabled} onChange={event=>setConfig({...config,enabled:event.target.checked})} className="ml-2 accent-primary"/></label><label className="text-xs">발송일 (매월 1~28일)<input type="number" min={1} max={28} value={config.send_day} onChange={event=>setConfig({...config,send_day:Number(event.target.value)})} className="mt-1 block w-full rounded-md border px-3 py-2"/></label><label className="text-xs">수신자 (쉼표로 구분)<input type="text" value={config.recipients} onChange={event=>setConfig({...config,recipients:event.target.value})} className="mt-1 block w-full rounded-md border px-3 py-2"/></label><label className="text-xs">CC (쉼표로 구분)<input type="text" value={config.cc} onChange={event=>setConfig({...config,cc:event.target.value})} className="mt-1 block w-full rounded-md border px-3 py-2"/></label><label className="text-xs">발송시간 · Asia/Seoul<input type="time" value={config.send_time} onChange={event=>setConfig({...config,send_time:event.target.value})} className="mt-1 block w-full rounded-md border px-3 py-2"/></label><label className="text-xs">제목 템플릿 · {"{month}"} 사용<input type="text" value={config.subject_template} onChange={event=>setConfig({...config,subject_template:event.target.value})} className="mt-1 block w-full rounded-md border px-3 py-2"/></label><div className="sm:col-span-2"><Button type="submit" disabled={busy}>발송 설정 저장</Button></div></form></CardContent></Card>}</div>}
