"use client";
import {useState} from "react";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {CommandForm,type Field} from "@/components/command-form";
import type {z} from "zod";
import type {cardSchema,cardAssignmentSchema} from "@/modules/corporate-card/infrastructure/repository";
import type {projectSchema} from "@/modules/project/infrastructure/repository";
type CorporateCard=z.infer<typeof cardSchema>;type Assignment=z.infer<typeof cardAssignmentSchema>;type Project=z.infer<typeof projectSchema>;
export function CorporateCardClient({cards,assignments,projects,people,canManage}:{cards:CorporateCard[];assignments:Assignment[];projects:Project[];people:{id:string;name:string}[];canManage:boolean}){const [editingCard,setEditingCard]=useState<CorporateCard|null>(null),[editingAssignment,setEditingAssignment]=useState<Assignment|null>(null);const cardName=new Map(cards.map(card=>[card.id,card.card_name]));const projectName=new Map(projects.map(project=>[project.id,project.project_name]));const personName=new Map(people.map(person=>[person.id,person.name]));
 const cardFields:Field[]=[{name:"card_name",label:"카드명",value:editingCard?.card_name,required:true},{name:"card_company",label:"카드사",value:editingCard?.card_company,required:true},{name:"identifier",label:"사내 관리 식별자",value:editingCard?.identifier,required:true},{name:"last_four",label:"카드 끝 4자리",value:editingCard?.last_four,required:true,minLength:4},{name:"status",label:"상태",type:"select",value:editingCard?.status??"ACTIVE",required:true,options:[{value:"ACTIVE",label:"사용 중"},{value:"INACTIVE",label:"사용 중지"},{value:"LOST",label:"분실"}]},{name:"memo",label:"메모",value:editingCard?.memo??""}];
 const assignmentFields:Field[]=[{name:"corporate_card_id",label:"법인카드",type:"select",value:editingAssignment?.corporate_card_id,required:true,options:cards.filter(card=>card.status==="ACTIVE"||card.id===editingAssignment?.corporate_card_id).map(card=>({value:card.id,label:`${card.card_name} ···· ${card.last_four}`}))},{name:"project_id",label:"프로젝트",type:"select",value:editingAssignment?.project_id,required:true,options:projects.map(project=>({value:project.id,label:`${project.project_code} ${project.project_name}`}))},{name:"responsible_user_id",label:"책임 직원",type:"select",value:editingAssignment?.responsible_user_id,required:true,options:people.map(person=>({value:person.id,label:person.name}))},{name:"assigned_from",label:"할당 시작일",type:"date",value:editingAssignment?.assigned_from,required:true},{name:"assigned_to",label:"할당 종료일",type:"date",value:editingAssignment?.assigned_to??""},{name:"status",label:"상태",type:"select",value:editingAssignment?.status??"ACTIVE",required:true,options:[{value:"ACTIVE",label:"사용 중"},{value:"ENDED",label:"종료"}]},{name:"memo",label:"메모",value:editingAssignment?.memo??""}];
 return <div className="grid gap-5 xl:grid-cols-2"><div className="space-y-5"><Card><CardHeader><CardTitle>등록된 법인카드</CardTitle></CardHeader><CardContent className="space-y-2">{cards.map(card=><div key={card.id} className="flex items-center justify-between rounded-md border p-3 text-xs"><div><p className="font-semibold">{card.card_name} ···· {card.last_four}</p><p className="mt-1 text-muted-foreground">{card.card_company} · {card.identifier}</p></div><div className="flex items-center gap-2"><Badge variant="outline">{card.status}</Badge>{canManage&&<Button variant="outline" size="sm" onClick={()=>setEditingCard(card)}>수정</Button>}</div></div>)}{!cards.length&&<p className="text-xs text-muted-foreground">등록된 카드가 없습니다.</p>}</CardContent></Card>{canManage&&<Card><CardHeader><CardTitle>{editingCard?"법인카드 수정":"법인카드 등록"}</CardTitle></CardHeader><CardContent><CommandForm key={editingCard?.id??"new"} endpoint="/api/corporate-card" action="card.save" constants={editingCard?{id:editingCard.id,version:editingCard.version}:{}} fields={cardFields} submit="카드 저장"/>{editingCard&&<Button variant="ghost" size="sm" className="mt-2" onClick={()=>setEditingCard(null)}>새 카드 입력</Button>}</CardContent></Card>}</div><div className="space-y-5"><Card><CardHeader><CardTitle>프로젝트 할당 이력</CardTitle></CardHeader><CardContent className="space-y-2">{assignments.map(item=><div key={item.id} className="flex items-center justify-between rounded-md border p-3 text-xs"><div><p className="font-semibold">{cardName.get(item.corporate_card_id)??"카드"} → {projectName.get(item.project_id)??"프로젝트"}</p><p className="mt-1 text-muted-foreground">{item.assigned_from} ~ {item.assigned_to??"진행 중"} · {personName.get(item.responsible_user_id)??"직원"}</p></div><div className="flex items-center gap-2"><Badge variant="outline">{item.status}</Badge>{canManage&&item.status==="ACTIVE"&&<Button variant="outline" size="sm" onClick={()=>setEditingAssignment(item)}>수정</Button>}</div></div>)}{!assignments.length&&<p className="text-xs text-muted-foreground">카드 할당 이력이 없습니다.</p>}</CardContent></Card>{canManage&&<Card><CardHeader><CardTitle>{editingAssignment?"할당 변경 / 종료":"프로젝트에 카드 할당"}</CardTitle></CardHeader><CardContent><CommandForm key={editingAssignment?.id??"new"} endpoint="/api/corporate-card" action="card_assignment.save" constants={editingAssignment?{id:editingAssignment.id,version:editingAssignment.version}:{}} fields={assignmentFields} submit="할당 저장"/>{editingAssignment&&<Button variant="ghost" size="sm" className="mt-2" onClick={()=>setEditingAssignment(null)}>새 할당 입력</Button>}</CardContent></Card>}</div></div>}
