"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Button} from "@/components/ui/button";
import {Badge} from "@/components/ui/badge";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";
import {CommandForm,type Field} from "@/components/command-form";
import {expenseCategories,expenseCategoryLabels} from "@/modules/corporate-card/domain/contracts";
import type {z} from "zod";
import type {cardSchema,cardAssignmentSchema,expenseSchema} from "@/modules/corporate-card/infrastructure/repository";
type CorporateCard=z.infer<typeof cardSchema>;type Assignment=z.infer<typeof cardAssignmentSchema>;type Expense=z.infer<typeof expenseSchema>;
type Summary={month_amount:number;project_amount:number;by_category:Record<string,number>;by_user:Record<string,number>;by_card:Record<string,number>};
const money=(value:number)=>`${value.toLocaleString("ko-KR")}원`;
export function ProjectExpensePanel({projectId,cards,assignments,expenses,summary,people,canWrite,canManage,today,accountId}:{projectId:string;cards:CorporateCard[];assignments:Assignment[];expenses:Expense[];summary:Summary|null;people:{id:string;name:string}[];canWrite:boolean;canManage:boolean;today:string;accountId:string}){const router=useRouter();const [editing,setEditing]=useState<Expense|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");const names=new Map(people.map(item=>[item.id,item.name]));const cardNames=new Map(cards.map(item=>[item.id,`${item.card_name} ···· ${item.last_four}`]));const eligible=assignments.filter(item=>item.project_id===projectId);const cardOptions=cards.filter(card=>eligible.some(item=>item.corporate_card_id===card.id)).map(card=>({value:card.id,label:cardNames.get(card.id)!}));const fields:Field[]=[{name:"transaction_date",label:"사용일자",type:"date",value:editing?.transaction_date??today,required:true},{name:"corporate_card_id",label:"법인카드",type:"select",value:editing?.corporate_card_id,required:true,options:cardOptions},{name:"merchant",label:"거래처",value:editing?.merchant,required:true},{name:"purpose",label:"사용 목적",value:editing?.purpose,required:true},{name:"category",label:"비용 구분",type:"select",value:editing?.category??"MEAL",required:true,options:expenseCategories.map(category=>({value:category,label:expenseCategoryLabels[category]}))},{name:"supply_amount",label:"공급가액",type:"number",value:editing?.supply_amount??0,min:0,step:0.01,required:true},{name:"vat_amount",label:"VAT",type:"number",value:editing?.vat_amount??0,min:0,step:0.01,required:true},{name:"memo",label:"비고",value:editing?.memo??""}];
 async function remove(expense:Expense){if(!confirm("이 비용 내역을 삭제하시겠습니까?"))return;setBusy(true);setMessage("");try{const response=await fetch("/api/corporate-card",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"expense.delete",payload:{id:expense.id,version:expense.version}})});const body=await response.json();if(!response.ok)throw new Error(body.error?.message??"삭제하지 못했습니다.");setMessage("삭제했습니다.");router.refresh()}catch(error){setMessage(error instanceof Error?error.message:"오류가 발생했습니다.")}finally{setBusy(false)}}
 async function upload(expense:Expense,file:File){setBusy(true);setMessage("");try{const form=new FormData();form.set("expense_id",expense.id);form.set("version",String(expense.version));form.set("file",file);const response=await fetch("/api/corporate-card/receipt",{method:"POST",body:form});const body=await response.json();if(!response.ok)throw new Error(body.error?.message??"업로드하지 못했습니다.");setMessage("영수증을 저장했습니다.");router.refresh()}catch(error){setMessage(error instanceof Error?error.message:"오류가 발생했습니다.")}finally{setBusy(false)}}
 return <div className="space-y-5">{summary&&<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["이번 달",summary.month_amount],["프로젝트 누적",summary.project_amount],...Object.entries(summary.by_category).slice(0,3).map(([category,amount])=>[expenseCategoryLabels[category as keyof typeof expenseCategoryLabels]??category,amount] as [string,number])].map(([label,value])=><Card key={label} className="gap-0 py-4"><CardContent><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-base font-semibold">{money(Number(value))}</p></CardContent></Card>)}</div>}
 {summary&&<Card><CardHeader><CardTitle>비용 분석</CardTitle></CardHeader><CardContent className="grid gap-4 text-xs sm:grid-cols-3"><div><p className="mb-2 font-semibold">비용 구분</p>{Object.entries(summary.by_category).map(([key,value])=><p key={key}>{expenseCategoryLabels[key as keyof typeof expenseCategoryLabels]??key} · {money(value)}</p>)}</div><div><p className="mb-2 font-semibold">직원별</p>{Object.entries(summary.by_user).map(([key,value])=><p key={key}>{key} · {money(value)}</p>)}</div><div><p className="mb-2 font-semibold">카드별</p>{Object.entries(summary.by_card).map(([key,value])=><p key={key}>{key} · {money(value)}</p>)}</div></CardContent></Card>}
 <Card><CardHeader><CardTitle>법인카드 사용내역</CardTitle></CardHeader><CardContent className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>사용일자</TableHead><TableHead>사용자</TableHead><TableHead>법인카드</TableHead><TableHead>거래처 / 목적</TableHead><TableHead>구분</TableHead><TableHead>합계</TableHead><TableHead>영수증</TableHead><TableHead/></TableRow></TableHeader><TableBody>{expenses.map(expense=><TableRow key={expense.id}><TableCell>{expense.transaction_date}</TableCell><TableCell>{names.get(expense.user_id)??"직원"}</TableCell><TableCell>{cardNames.get(expense.corporate_card_id)??"카드"}</TableCell><TableCell>{expense.merchant}<p className="text-[11px] text-muted-foreground">{expense.purpose}</p></TableCell><TableCell><Badge variant="outline">{expenseCategoryLabels[expense.category as keyof typeof expenseCategoryLabels]??expense.category}</Badge></TableCell><TableCell>{money(expense.total_amount)}</TableCell><TableCell>{expense.receipt_key?<a className="text-primary underline" href={`/api/corporate-card/receipt?id=${expense.id}`} target="_blank" rel="noreferrer">보기</a>:canWrite&&(canManage||expense.user_id===accountId)?<label className="cursor-pointer text-primary">등록<input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)void upload(expense,file)}}/></label>:"—"}</TableCell><TableCell>{canWrite&&(canManage||expense.user_id===accountId)&&<div className="flex gap-1"><Button size="sm" variant="outline" onClick={()=>setEditing(expense)}>수정</Button><Button size="sm" variant="ghost" disabled={busy} onClick={()=>void remove(expense)}>삭제</Button></div>}</TableCell></TableRow>)}</TableBody></Table>{!expenses.length&&<p className="p-5 text-xs text-muted-foreground">비용 내역이 없습니다.</p>}</CardContent></Card>
 {canWrite&&<Card><CardHeader><CardTitle>{editing?"비용 수정":"비용 등록"}</CardTitle></CardHeader><CardContent>{cardOptions.length?<CommandForm key={editing?.id??"new"} endpoint="/api/corporate-card" action="expense.save" constants={{project_id:projectId,...editing&&{id:editing.id,version:editing.version}}} fields={fields} submit="비용 저장"/>:<p className="text-xs text-muted-foreground">먼저 이 프로젝트에 법인카드를 할당해 주세요.</p>}{editing&&<Button className="mt-2" size="sm" variant="ghost" onClick={()=>setEditing(null)}>새 비용 입력</Button>}</CardContent></Card>}{message&&<p role="status" className="text-xs text-primary">{message}</p>}</div>}
