"use client";
import {useState} from "react";
import Link from "next/link";
import {Button} from "@/components/ui/button";
import {Badge} from "@/components/ui/badge";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";
import {CommandForm,type Field} from "@/components/command-form";
import {ResourceBoard} from "@/components/resource-board";
import {PlanningTimeline} from "@/components/planning-timeline";
import {actualProgress,dateNumber,plannedProgress} from "@/modules/project-resource/domain/metrics";
import {assignmentStatuses,assignmentStatusLabels,projectStatuses,projectStatusLabels} from "@/modules/project/domain/contracts";
import type {projectSchema,projectAssignmentSchema,taskSchema,milestoneSchema,issueSchema} from "@/modules/project/infrastructure/repository";
import type {workLogSchema} from "@/modules/work-management/infrastructure/repository";
import type {cardSchema,cardAssignmentSchema,expenseSchema} from "@/modules/corporate-card/infrastructure/repository";
import {ProjectExpensePanel} from "@/components/project-expense-panel";
import {ProjectStaffingPanel} from "@/components/project-staffing-panel";
import type {skillCatalog,staffingForProject} from "@/modules/workforce-profile/infrastructure/repository";
import type {z} from "zod";
type Project=z.infer<typeof projectSchema>;type Assignment=z.infer<typeof projectAssignmentSchema>;type Task=z.infer<typeof taskSchema>;type Milestone=z.infer<typeof milestoneSchema>;type Issue=z.infer<typeof issueSchema>;
type WorkLog=z.infer<typeof workLogSchema>;
type ExpenseData=[{cards:z.infer<typeof cardSchema>[];assignments:z.infer<typeof cardAssignmentSchema>[]},z.infer<typeof expenseSchema>[],{month_amount:number;project_amount:number;by_category:Record<string,number>;by_user:Record<string,number>;by_card:Record<string,number>}];
type Person={id:string;name:string;organization_id:string|null;position_id:string|null;title_id:string|null};
const taskStatuses=["PLANNED","IN_PROGRESS","ON_HOLD","DONE"] as const;const taskLabels={PLANNED:"예정",IN_PROGRESS:"진행 중",ON_HOLD:"보류",DONE:"완료"};
const milestoneStatuses=["PLANNED","IN_PROGRESS","COMPLETED","ON_HOLD"] as const;const milestoneLabels={PLANNED:"예정",IN_PROGRESS:"진행 중",COMPLETED:"완료",ON_HOLD:"보류"};
const issueStatuses=["OPEN","IN_PROGRESS","RESOLVED","CLOSED"] as const;const issueLabels={OPEN:"열림",IN_PROGRESS:"처리 중",RESOLVED:"해결",CLOSED:"종결"};
const priorities=["LOW","MEDIUM","HIGH","URGENT"] as const;const priorityLabels={LOW:"낮음",MEDIUM:"보통",HIGH:"높음",URGENT:"긴급"};
const opts=<T extends string>(values:readonly T[],labels:Record<T,string>)=>values.map(value=>({value,label:labels[value]}));
export function ProjectDetail({project,assignments,tasks,milestones,issues,workLogs,expenseData,canWriteExpense,canManageExpense,staffing,skills,canManageStaffing,canSearchStaffing,canExportProfiles,people,organizations,positions,titles,capacity,searchEnd,canWrite,canAssign,canReadAll,accountId,today}:{project:Project;assignments:Assignment[];tasks:Task[];milestones:Milestone[];issues:Issue[];workLogs:WorkLog[];expenseData:ExpenseData|null;canWriteExpense:boolean;canManageExpense:boolean;staffing:Awaited<ReturnType<typeof staffingForProject>>|null;skills:Awaited<ReturnType<typeof skillCatalog>>;canManageStaffing:boolean;canSearchStaffing:boolean;canExportProfiles:boolean;people:Person[];organizations:{id:string;name:string}[];positions:{id:string;name:string}[];titles:{id:string;name:string}[];capacity:{user_id:string;average_allocation:number;peak_allocation:number;minimum_availability:number}[];searchEnd:string;canWrite:boolean;canAssign:boolean;canReadAll:boolean;accountId:string;today:string}){
  const [tab,setTab]=useState<"overview"|"schedule"|"people"|"staffing"|"wbs"|"issues"|"work"|"expense">("overview"),[taskView,setTaskView]=useState<"list"|"gantt">("list"),[editingTask,setEditingTask]=useState<Task|null>(null),[editingMilestone,setEditingMilestone]=useState<Milestone|null>(null),[editingIssue,setEditingIssue]=useState<Issue|null>(null),[showLegacy,setShowLegacy]=useState(false);
  const selectedTask=editingTask?tasks.find(row=>row.id===editingTask.id)??editingTask:null;
  const selectedMilestone=editingMilestone?milestones.find(row=>row.id===editingMilestone.id)??editingMilestone:null;
  const selectedIssue=editingIssue?issues.find(row=>row.id===editingIssue.id)??editingIssue:null;
  const names=new Map(people.map(p=>[p.id,p.name]));const managerOptions=people.filter(p=>canReadAll||p.id===accountId);const plan=plannedProgress(project.planned_start_date,project.planned_end_date,today);const actual=actualProgress(project.actual_progress,tasks);const active=assignments.filter(a=>["PLANNED","CONFIRMED","IN_PROGRESS"].includes(a.status));const delayed=project.planned_end_date<today&&!["COMPLETED","CANCELED"].includes(project.status);const openIssues=issues.filter(i=>i.kind==="ISSUE"&&!['RESOLVED','CLOSED'].includes(i.status));const risks=issues.filter(i=>i.kind==="RISK"&&!['RESOLVED','CLOSED'].includes(i.status));const nextMilestone=milestones.find(m=>m.status!=="COMPLETED"&&m.planned_date>=today);
  const peopleOptions=[{value:"",label:"미지정"},...people.map(p=>({value:p.id,label:p.name}))];
  const tabItems=[["overview","개요"],["schedule","일정"],["people","투입 인력"],...staffing?[["staffing","인력 계획"] as const]:[],["wbs","업무 / WBS"],["issues","이슈 / 리스크"],["work","업무 기록"],...expenseData?[["expense","비용 / 법인카드"] as const]:[]] as const;
  const taskFields=(task:Task|null):Field[]=>[
    {name:"title",label:"업무명",value:task?.title,required:true},{name:"parent_id",label:"상위 업무",type:"select",value:task?.parent_id??"",options:tasks.filter(t=>t.id!==task?.id).map(t=>({value:t.id,label:t.title}))},
    {name:"assignee_id",label:"담당자",type:"select",value:task?.assignee_id??"",options:peopleOptions},{name:"status",label:"상태",type:"select",value:task?.status??"PLANNED",options:opts(taskStatuses,taskLabels)},
    {name:"priority",label:"우선순위",type:"select",value:task?.priority??"MEDIUM",options:opts(priorities,priorityLabels)},
    {name:"planned_start_date",label:"계획 시작일",type:"date",value:task?.planned_start_date??project.planned_start_date,required:true},
    {name:"planned_end_date",label:"계획 종료일",type:"date",value:task?.planned_end_date??project.planned_end_date,required:true},
    {name:"actual_start_date",label:"실제 시작일",type:"date",value:task?.actual_start_date??""},{name:"actual_end_date",label:"실제 종료일",type:"date",value:task?.actual_end_date??""},
    {name:"progress",label:"진행률 (%)",type:"number",min:0,max:100,value:task?.progress??0,required:true},{name:"description",label:"설명",value:task?.description??""},
  ];
  const milestoneFields=(m:Milestone|null):Field[]=>[
    {name:"name",label:"마일스톤 이름",value:m?.name,required:true},{name:"planned_date",label:"예정일",type:"date",value:m?.planned_date??project.planned_end_date,required:true},
    {name:"completed_date",label:"완료일",type:"date",value:m?.completed_date??""},{name:"status",label:"상태",type:"select",value:m?.status??"PLANNED",options:opts(milestoneStatuses,milestoneLabels)},
    {name:"description",label:"설명",value:m?.description??""},
  ];
  const issueFields=(i:Issue|null):Field[]=>[
    {name:"kind",label:"유형",type:"select",value:i?.kind??"ISSUE",options:[{value:"ISSUE",label:"Issue"},{value:"RISK",label:"Risk"}]},
    {name:"title",label:"제목",value:i?.title,required:true},{name:"description",label:"내용",value:i?.description??""},{name:"assignee_id",label:"담당자",type:"select",value:i?.assignee_id??"",options:peopleOptions},
    {name:"priority",label:"우선순위",type:"select",value:i?.priority??"MEDIUM",options:opts(priorities,priorityLabels)},
    {name:"status",label:"상태",type:"select",value:i?.status??"OPEN",options:opts(issueStatuses,issueLabels)},
    {name:"target_date",label:"목표 해결일",type:"date",value:i?.target_date??""},{name:"resolved_date",label:"해결일",type:"date",value:i?.resolved_date??""},
  ];
  const fields:Field[]=[
    {name:"project_code",label:"프로젝트 코드",value:project.project_code,required:true},{name:"project_name",label:"프로젝트명",value:project.project_name,required:true},
    {name:"customer_name",label:"고객사",value:project.customer_name,required:true},{name:"description",label:"설명",value:project.description??""},
    {name:"planned_start_date",label:"계획 시작일",type:"date",value:project.planned_start_date,required:true},{name:"planned_end_date",label:"계획 종료일",type:"date",value:project.planned_end_date,required:true},
    {name:"actual_start_date",label:"실제 시작일",type:"date",value:project.actual_start_date??""},{name:"actual_end_date",label:"실제 종료일",type:"date",value:project.actual_end_date??""},
    {name:"status",label:"상태",type:"select",value:project.status,required:true,options:opts(projectStatuses,projectStatusLabels)},
    {name:"project_manager_id",label:"PM",type:"select",value:project.project_manager_id,required:true,options:managerOptions.map(p=>({value:p.id,label:p.name}))},
  ];
  const sortedTasks=[...tasks].sort((a,b)=>a.planned_start_date.localeCompare(b.planned_start_date));
  const ordered: {task:Task;depth:number}[]=[];const seen=new Set<string>();
  const append=(parent:string|null,depth:number)=>{for(const task of sortedTasks.filter(t=>t.parent_id===parent)){if(seen.has(task.id))continue;seen.add(task.id);ordered.push({task,depth});append(task.id,depth+1)}};
  append(null,0);for(const task of sortedTasks)if(!seen.has(task.id)){ordered.push({task,depth:0});append(task.id,1)}
  const rangeStart=[project.planned_start_date,...tasks.map(t=>t.planned_start_date),...milestones.map(m=>m.planned_date)].sort()[0];
  const rangeEnd=[project.planned_end_date,...tasks.map(t=>t.planned_end_date),...milestones.map(m=>m.planned_date)].sort().at(-1)!;
  const ganttCount=Math.max(1,dateNumber(rangeEnd)-dateNumber(rangeStart)+1);
  const gantt=<div className="overflow-x-auto rounded-md border"><div className="min-w-[760px]"><div className="flex border-b bg-muted text-xs"><span className="w-44 shrink-0 p-3">업무 / 마일스톤</span><span className="p-3">{rangeStart} ~ {rangeEnd}</span></div>{ordered.map(({task,depth})=>{const left=(dateNumber(task.planned_start_date)-dateNumber(rangeStart))/ganttCount*100,width=(dateNumber(task.planned_end_date)-dateNumber(task.planned_start_date)+1)/ganttCount*100;return <div key={task.id} className="flex border-b text-xs"><span className="w-44 shrink-0 truncate border-r p-2" style={{paddingLeft:8+Math.min(depth,5)*14}} title={task.title}>{task.title}</span><div className="relative h-8 flex-1 bg-card"><span title={`${task.title} · ${task.planned_start_date} ~ ${task.planned_end_date} · ${task.progress}%`} className="absolute top-2 h-4 rounded bg-primary/80 text-[10px] text-white" style={{left:`${left}%`,width:`${Math.max(width,0.6)}%`}}><span className="px-1">{task.progress}%</span></span></div></div>})}{milestones.map(m=><div key={m.id} className="flex border-b text-xs"><span className="w-44 shrink-0 truncate border-r p-2">◆ {m.name}</span><div className="relative h-8 flex-1 bg-card"><span title={`${m.name} · ${m.planned_date}`} className="absolute top-1 text-lg text-brand-navy" style={{left:`${(dateNumber(m.planned_date)-dateNumber(rangeStart))/ganttCount*100}%`}}>◆</span></div></div>)}{!tasks.length&&!milestones.length&&<p className="p-5 text-xs text-muted-foreground">업무와 마일스톤을 등록하면 일정이 표시됩니다.</p>}</div></div>;
  return <>
    <div className="mb-4 flex items-center gap-3"><Link href="/admin/projects" className="text-xs text-primary">← 프로젝트 목록</Link><Badge variant="outline" className={delayed?"border-destructive text-destructive":""}>{delayed?"일정 지연":projectStatusLabels[project.status as keyof typeof projectStatusLabels]}</Badge></div>
    <div className="mb-5 grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-8">{[
      ["기간",`${project.planned_start_date} ~ ${project.planned_end_date}`],["남은 기간",`${Math.max(0,dateNumber(project.planned_end_date)-dateNumber(today))}일`],
      ["계획 진행률",`${plan}%`],["실제 진행률",`${actual}%`],["투입 인원",`${new Set(active.map(a=>a.user_id)).size}명`],
      ["평균 투입률",`${active.length?Math.round(active.reduce((sum,a)=>sum+a.allocation_rate,0)/active.length):0}%`],
      ["Open Issue / Risk",`${openIssues.length} / ${risks.length}`],["다음 Milestone",nextMilestone?`${nextMilestone.name} · ${nextMilestone.planned_date}`:"—"],
    ].map(([label,value])=><Card key={label} className="gap-0 py-4"><CardContent className="px-4"><p className="text-[11px] text-muted-foreground">{label}</p><p className="mt-2 text-xs font-semibold break-words">{value}</p></CardContent></Card>)}</div>
    {(tasks.length>0||project.actual_progress!==null)&&actual<plan-15&&project.status==="IN_PROGRESS"&&<p className="mb-4 rounded-md border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">계획 진행률보다 실제 진행률이 {plan-actual}%p 낮습니다. 일정을 확인해 주세요.</p>}
    <div role="tablist" aria-label="프로젝트 상세" className="mb-5 flex flex-wrap gap-2 border-b pb-3">{tabItems.map(([key,label])=><Button key={key} role="tab" aria-selected={tab===key} variant={tab===key?"default":"outline"} size="sm" onClick={()=>setTab(key)}>{label}</Button>)}</div>
    {tab==="staffing"&&staffing&&<ProjectStaffingPanel projectId={project.id} start={project.planned_start_date} end={searchEnd} staffing={staffing} skills={skills} assignments={assignments} people={people} organizations={organizations} positions={positions} canManage={canManageStaffing} canSearch={canSearchStaffing} canExportProfiles={canExportProfiles} onOpenPeople={()=>setTab("people")}/>}
    {tab==="overview"&&<div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><CardTitle>프로젝트 정보</CardTitle></CardHeader><CardContent>{canWrite?<CommandForm key={project.version} endpoint="/api/project-resource" action="project.save" constants={{id:project.id,version:project.version}} fields={fields} submit="프로젝트 저장"/>:<div className="space-y-2 text-xs"><p>PM {names.get(project.project_manager_id)??"—"}</p><p>{project.description??"설명 없음"}</p><p>실제 기간 {project.actual_start_date??"—"} ~ {project.actual_end_date??"—"}</p></div>}</CardContent></Card><div className="space-y-5"><Card><CardHeader><CardTitle>주요 일정</CardTitle></CardHeader><CardContent className="space-y-2 text-xs">{milestones.slice(0,5).map(m=><p key={m.id}>{m.planned_date} · {m.name} <Badge variant="outline">{milestoneLabels[m.status as keyof typeof milestoneLabels]}</Badge></p>)}{!milestones.length&&"마일스톤이 없습니다."}</CardContent></Card><Card><CardHeader><CardTitle>최근 Issue / 투입 인력</CardTitle></CardHeader><CardContent className="space-y-2 text-xs">{openIssues.slice(0,3).map(i=><p key={i.id}>• {i.title}</p>)}<p className="border-t pt-2 text-muted-foreground">{[...new Set(active.map(a=>names.get(a.user_id)??"조회 제한"))].join(", ")||"등록된 인력이 없습니다."}</p></CardContent></Card></div></div>}
    {tab==="schedule"&&<div className="space-y-5"><Card><CardHeader><CardTitle>프로젝트 일정 / 진행률</CardTitle></CardHeader><CardContent><p className="mb-3 text-xs">계획 {plan}% · 실제 {actual}% {project.actual_progress!==null?"(PM 수동 입력)":"(WBS 하위 업무 평균)"}</p>{canWrite&&<CommandForm key={project.version} endpoint="/api/project-resource" action="project.progress" constants={{project_id:project.id,version:project.version}} fields={[{name:"actual_progress",label:"실제 진행률 (%)",type:"number",min:0,max:100,value:actual,required:true}]} submit="진행률 저장"/>}</CardContent></Card><Card><CardHeader><CardTitle>프로젝트 Gantt</CardTitle></CardHeader><CardContent>{gantt}</CardContent></Card><Card><CardHeader><CardTitle>마일스톤</CardTitle></CardHeader><CardContent><div className="mb-4 space-y-2">{milestones.map(m=><div key={m.id} className="flex items-center justify-between rounded border p-2 text-xs"><span>{m.planned_date} · {m.name} · {milestoneLabels[m.status as keyof typeof milestoneLabels]} {m.completed_date&&`· 완료 ${m.completed_date}`}</span>{canAssign&&<Button size="sm" variant="outline" onClick={()=>setEditingMilestone(m)}>수정</Button>}</div>)}</div>{canAssign&&<><h3 className="mb-3 text-xs font-semibold">{selectedMilestone?"마일스톤 수정":"마일스톤 추가"}</h3><CommandForm key={selectedMilestone?.id+":"+selectedMilestone?.version} endpoint="/api/project-resource" action="project_milestone.save" constants={{project_id:project.id,...selectedMilestone&&{id:selectedMilestone.id,version:selectedMilestone.version}}} fields={milestoneFields(selectedMilestone)} submit="마일스톤 저장"/>{selectedMilestone&&<Button className="mt-2" variant="ghost" size="sm" onClick={()=>setEditingMilestone(null)}>새 항목 입력</Button>}</>}</CardContent></Card></div>}
    {tab==="people"&&<div className="space-y-5"><ResourceBoard projectId={project.id} assignments={assignments} people={people} organizations={organizations} positions={positions} titles={titles} initialCapacity={capacity} plannedStart={project.planned_start_date} plannedEnd={searchEnd} canAssign={canAssign}/><Card><CardHeader><CardTitle>Resource Timeline</CardTitle></CardHeader><CardContent><PlanningTimeline start={project.planned_start_date} end={project.planned_end_date} assignments={assignments} people={people} projects={[project]} editable={canAssign}/></CardContent></Card>{canAssign&&<Card><CardHeader><Button size="sm" variant="outline" onClick={()=>setShowLegacy(!showLegacy)}>{showLegacy?"기존 입력 닫기":"기존 직원별 투입 입력"}</Button></CardHeader>{showLegacy&&<CardContent><CommandForm endpoint="/api/project-resource" action="project_assignment.save" constants={{project_id:project.id}} fields={[
      {name:"user_id",label:"직원",type:"select",required:true,options:people.map(p=>({value:p.id,label:p.name}))},{name:"project_role",label:"프로젝트 역할",required:true},
      {name:"planned_start_date",label:"계획 시작일",type:"date",value:project.planned_start_date,required:true},{name:"planned_end_date",label:"계획 종료일",type:"date",value:project.planned_end_date,required:true},
      {name:"actual_start_date",label:"실제 시작일",type:"date"},{name:"actual_end_date",label:"실제 종료일",type:"date"},
      {name:"allocation_rate",label:"투입률 (%)",type:"number",value:100,min:0,max:100,step:0.01,required:true},{name:"status",label:"상태",type:"select",value:"PLANNED",options:opts(assignmentStatuses,assignmentStatusLabels)},{name:"memo",label:"메모"},
    ]} submit="투입 이력 추가"/></CardContent>}</Card>}</div>}
    {tab==="wbs"&&<div className="space-y-5"><Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle>업무 / WBS</CardTitle><div className="flex gap-2"><Button size="sm" variant={taskView==="list"?"default":"outline"} onClick={()=>setTaskView("list")}>목록</Button><Button size="sm" variant={taskView==="gantt"?"default":"outline"} onClick={()=>setTaskView("gantt")}>Gantt</Button></div></CardHeader><CardContent>{taskView==="gantt"?gantt:<div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>업무</TableHead><TableHead>담당자</TableHead><TableHead>상태</TableHead><TableHead>우선순위</TableHead><TableHead>계획 기간</TableHead><TableHead>진행률</TableHead><TableHead/></TableRow></TableHeader><TableBody>{ordered.map(({task,depth})=><TableRow key={task.id}><TableCell style={{paddingLeft:12+Math.min(depth,5)*18}} className="font-semibold">{depth?"└ ":""}{task.title}</TableCell><TableCell>{names.get(task.assignee_id??"")??"—"}</TableCell><TableCell><Badge variant="outline">{taskLabels[task.status as keyof typeof taskLabels]}</Badge></TableCell><TableCell>{priorityLabels[task.priority as keyof typeof priorityLabels]}</TableCell><TableCell>{task.planned_start_date} ~ {task.planned_end_date}</TableCell><TableCell>{task.progress}%</TableCell><TableCell>{canAssign&&<Button variant="outline" size="sm" onClick={()=>setEditingTask(task)}>수정</Button>}</TableCell></TableRow>)}</TableBody></Table>{!tasks.length&&<p className="p-5 text-xs text-muted-foreground">업무가 없습니다.</p>}</div>}</CardContent></Card>{canAssign&&<Card><CardHeader><CardTitle>{selectedTask?"업무 수정":"업무 추가"}</CardTitle></CardHeader><CardContent><CommandForm key={selectedTask?.id+":"+selectedTask?.version} endpoint="/api/project-resource" action="project_task.save" constants={{project_id:project.id,...selectedTask&&{id:selectedTask.id,version:selectedTask.version}}} fields={taskFields(selectedTask)} submit="업무 저장"/>{selectedTask&&<Button variant="ghost" size="sm" className="mt-2" onClick={()=>setEditingTask(null)}>새 업무 입력</Button>}</CardContent></Card>}</div>}
    {tab==="issues"&&<div className="space-y-5"><Card><CardHeader><CardTitle>이슈 / 리스크</CardTitle></CardHeader><CardContent className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>유형 / 제목</TableHead><TableHead>담당자</TableHead><TableHead>우선순위</TableHead><TableHead>상태</TableHead><TableHead>등록일</TableHead><TableHead>목표 / 해결일</TableHead><TableHead/></TableRow></TableHeader><TableBody>{issues.map(i=><TableRow key={i.id}><TableCell><Badge variant="outline">{i.kind}</Badge> {i.title}<p className="mt-1 text-[11px] text-muted-foreground">{i.description}</p></TableCell><TableCell>{names.get(i.assignee_id??"")??"—"}</TableCell><TableCell>{priorityLabels[i.priority as keyof typeof priorityLabels]}</TableCell><TableCell>{issueLabels[i.status as keyof typeof issueLabels]}</TableCell><TableCell>{i.created_at.slice(0,10)}</TableCell><TableCell>{i.target_date??"—"} / {i.resolved_date??"—"}</TableCell><TableCell>{canAssign&&<Button size="sm" variant="outline" onClick={()=>setEditingIssue(i)}>수정</Button>}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>{canAssign&&<Card><CardHeader><CardTitle>{selectedIssue?"이슈 / 리스크 수정":"이슈 / 리스크 등록"}</CardTitle></CardHeader><CardContent><CommandForm key={selectedIssue?.id+":"+selectedIssue?.version} endpoint="/api/project-resource" action="project_issue.save" constants={{project_id:project.id,...selectedIssue&&{id:selectedIssue.id,version:selectedIssue.version}}} fields={issueFields(selectedIssue)} submit="저장"/>{selectedIssue&&<Button variant="ghost" size="sm" className="mt-2" onClick={()=>setEditingIssue(null)}>새 항목 입력</Button>}</CardContent></Card>}</div>}
    {tab==="work"&&<Card><CardHeader><CardTitle>프로젝트 업무 기록</CardTitle></CardHeader><CardContent><p className="mb-3 text-xs text-muted-foreground">최근 1년의 이 프로젝트와 연결된 업무일지만 표시합니다. 업무일지는 직원이 업무관리에서 작성합니다.</p><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>일자</TableHead><TableHead>직원</TableHead><TableHead>업무</TableHead><TableHead>시간</TableHead><TableHead>상태</TableHead></TableRow></TableHeader><TableBody>{workLogs.map(log=><TableRow key={log.id}><TableCell>{log.work_date}</TableCell><TableCell>{names.get(log.user_id)??"직원"}</TableCell><TableCell>{log.title}<p className="mt-1 text-[11px] text-muted-foreground">{log.description}</p></TableCell><TableCell>{Math.round(log.work_minutes/60*10)/10}시간</TableCell><TableCell>{log.status}</TableCell></TableRow>)}</TableBody></Table>{!workLogs.length&&<p className="p-5 text-xs text-muted-foreground">연결된 업무 기록이 없습니다.</p>}</div></CardContent></Card>}
    {tab==="expense"&&expenseData&&<ProjectExpensePanel projectId={project.id} cards={expenseData[0].cards} assignments={expenseData[0].assignments} expenses={expenseData[1]} summary={expenseData[2]} people={people} canWrite={canWriteExpense} canManage={canManageExpense} today={today} accountId={accountId}/>}
  </>;
}
