"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Badge} from "@/components/ui/badge";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {assignmentStatusLabels,assignmentStatuses} from "@/modules/project/domain/contracts";
import {allocationLabel,dateNumber} from "@/modules/project-resource/domain/metrics";
import type {projectAssignmentSchema} from "@/modules/project/infrastructure/repository";
import type {z} from "zod";
type Assignment=z.infer<typeof projectAssignmentSchema>;
type Person={id:string;name:string;organization_id:string|null;position_id:string|null;title_id:string|null};
type Capacity={user_id:string;average_allocation:number;peak_allocation:number;minimum_availability:number};
export function ResourceBoard({projectId,assignments,people,organizations,positions,titles,initialCapacity,plannedStart,plannedEnd,canAssign}:{projectId:string;assignments:Assignment[];people:Person[];organizations:{id:string;name:string}[];positions:{id:string;name:string}[];titles:{id:string;name:string}[];initialCapacity:Capacity[];plannedStart:string;plannedEnd:string;canAssign:boolean}){
  const router=useRouter();const [start,setStart]=useState(plannedStart),[end,setEnd]=useState(plannedEnd),[search,setSearch]=useState(""),[org,setOrg]=useState(""),[position,setPosition]=useState(""),[title,setTitle]=useState(""),[minimum,setMinimum]=useState(0);
  const [capacity,setCapacity]=useState(initialCapacity),[selected,setSelected]=useState<string[]>([]),[editing,setEditing]=useState<Assignment|null>(null),[dialog,setDialog]=useState(false);
  const [role,setRole]=useState(""),[rate,setRate]=useState(50),[memo,setMemo]=useState(""),[status,setStatus]=useState("PLANNED"),[actualStart,setActualStart]=useState(""),[actualEnd,setActualEnd]=useState("");
  const [busy,setBusy]=useState(false),[message,setMessage]=useState("");
  useEffect(()=>{if(!start||!end||start>end||dateNumber(end)-dateNumber(start)>185)return;const controller=new AbortController();const timer=setTimeout(async()=>{
    try{const response=await fetch(`/api/resource-capacity?start=${start}&end=${end}&granularity=range`,{signal:controller.signal});const body=await response.json();if(response.ok)setCapacity(body.data??[])}catch{/* Keep the last capacity result while dates change. */}
  },250);return()=>{clearTimeout(timer);controller.abort()}},[start,end]);
  const capacities=new Map(capacity.map(row=>[row.user_id,row]));const names=new Map(people.map(p=>[p.id,p.name]));const orgNames=new Map(organizations.map(o=>[o.id,o.name]));
  const validRange=!!start&&!!end&&dateNumber(end)>=dateNumber(start)&&dateNumber(end)-dateNumber(start)<=185;
  const filtered=people.filter(person=>person.name.toLowerCase().includes(search.toLowerCase())&&(!org||person.organization_id===org)&&(!position||person.position_id===position)&&(!title||person.title_id===title)&&(!validRange||((capacities.get(person.id)?.minimum_availability??100)>=minimum)));
  const open=(ids:string[],row:Assignment|null=null)=>{setSelected(ids);setEditing(row);setRole(row?.project_role??"");setStart(row?.planned_start_date??start);setEnd(row?.planned_end_date??end);setRate(row?.allocation_rate??50);setMemo(row?.memo??"");setStatus(row?.status??"PLANNED");setActualStart(row?.actual_start_date??"");setActualEnd(row?.actual_end_date??"");setMessage("");setDialog(true)};
  async function save(payload:Record<string,unknown>,action:string){setBusy(true);setMessage("");try{
    const response=await fetch("/api/project-resource",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,payload})});const body=await response.json();
    if(!response.ok)throw new Error(body.error?.message??"저장하지 못했습니다.");
    const warning=body.data?.over_allocated?" · 100% 초과 투입이 발생했습니다.":"";
    setMessage((body.data?.message??"저장했습니다.")+warning);setDialog(false);setSelected([]);router.refresh();
  }catch(error){setMessage(error instanceof Error?error.message:"연결을 확인해 주세요.")}finally{setBusy(false)}}
  const candidate=selected[0]?capacities.get(selected[0]):undefined;
  const predicted=(candidate?.peak_allocation??0)+rate-(editing&&editing.user_id===selected[0]?editing.allocation_rate:0);
  return <>
    <div className="mb-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs">검색 시작일<Input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="text-xs">검색 종료일<Input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label className="text-xs">최소 가용률 (%)<Input type="number" min={0} max={100} value={minimum} onChange={e=>setMinimum(Number(e.target.value))}/></label><p className="self-end text-xs text-muted-foreground">선택 기간의 최저 가용률로 검색합니다.</p></div>
    {!validRange&&<p role="alert" className="mb-3 text-xs text-destructive">가용률 검색 기간은 186일 이내로 설정해 주세요.</p>}
    <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle>투입 가능 직원</CardTitle>{canAssign&&<Button size="sm" disabled={!selected.length} onClick={()=>open(selected)}>선택 직원 투입 ({selected.length})</Button>}</CardHeader><CardContent>
      <div className="grid gap-2 sm:grid-cols-2"><Input aria-label="직원 검색" placeholder="직원 검색" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="조직 필터" value={org} onChange={e=>setOrg(e.target.value)}><option value="">전체 조직</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select><select aria-label="직급 필터" value={position} onChange={e=>setPosition(e.target.value)}><option value="">전체 직급</option>{positions.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select aria-label="직무 필터" value={title} onChange={e=>setTitle(e.target.value)}><option value="">전체 직무</option>{titles.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div>
      <div className="mt-3 max-h-[520px] space-y-2 overflow-y-auto">{filtered.map(person=>{const cap=capacities.get(person.id);return <div key={person.id} draggable={canAssign} onDragStart={e=>e.dataTransfer.setData("text/plain",person.id)} className="flex items-center gap-3 rounded-md border p-3 text-xs"><input aria-label={`${person.name} 선택`} type="checkbox" checked={selected.includes(person.id)} onChange={e=>setSelected(e.target.checked?[...selected,person.id]:selected.filter(id=>id!==person.id))}/><div className="min-w-0 flex-1"><p className="font-semibold">{person.name} <span className="font-normal text-muted-foreground">{orgNames.get(person.organization_id??"")??"미배정"}</span></p><p className="mt-1 text-muted-foreground">{validRange?`평균 투입 ${cap?.average_allocation??0}% · 최저 가용 ${cap?.minimum_availability??100}%`:"조회 기간을 조정해 주세요."}</p></div>{canAssign&&<Button size="sm" variant="outline" onClick={()=>open([person.id])}>투입하기</Button>}</div>})}{!filtered.length&&<p className="py-6 text-center text-xs text-muted-foreground">조건에 맞는 직원이 없습니다.</p>}</div>
    </CardContent></Card>
    <Card onDragOver={e=>{if(canAssign)e.preventDefault()}} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData("text/plain");if(canAssign&&people.some(p=>p.id===id))open([id])}}><CardHeader><CardTitle>프로젝트 투입 인력 <span className="text-xs font-normal text-muted-foreground">이곳으로 직원을 끌어 놓으세요</span></CardTitle></CardHeader><CardContent className="max-h-[620px] space-y-2 overflow-y-auto">{assignments.map(row=><div key={row.id} className="flex items-center gap-3 rounded-md border p-3 text-xs"><div className="min-w-0 flex-1"><p className="font-semibold">{names.get(row.user_id)??"조회 제한"} <Badge variant="outline">{assignmentStatusLabels[row.status as keyof typeof assignmentStatusLabels]??row.status}</Badge></p><p className="mt-1 text-muted-foreground">{row.project_role} · {row.planned_start_date} ~ {row.planned_end_date} · {row.allocation_rate}% ({allocationLabel(row.allocation_rate)})</p></div>{canAssign&&<><Button size="sm" variant="outline" onClick={()=>open([row.user_id],row)}>수정</Button>{row.status!=="CANCELED"&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>{if(confirm(`${names.get(row.user_id)} 투입을 취소하시겠습니까?`))void save({...row,status:"CANCELED",memo:row.memo??"",actual_start_date:row.actual_start_date??"",actual_end_date:row.actual_end_date??""},"project_assignment.save")}}>제거</Button>}</>}</div>)}{!assignments.length&&<p className="py-8 text-center text-xs text-muted-foreground">아직 투입된 직원이 없습니다.</p>}</CardContent></Card></div>
    {message&&!dialog&&<p role="status" className="mt-3 text-xs text-primary">{message}</p>}
    {dialog&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-brand-navy/40 p-4" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setDialog(false)}}><form role="dialog" aria-modal="true" aria-label="직원 투입 설정" onKeyDown={e=>{if(e.key==="Escape")setDialog(false)}} className="w-full max-w-lg space-y-4 rounded-lg border bg-card p-6 shadow-xl" onSubmit={e=>{e.preventDefault();if(end<start){setMessage("종료일을 시작일 이후로 설정해 주세요.");return}const base={project_id:projectId,project_role:role,planned_start_date:start,planned_end_date:end,allocation_rate:rate,status,memo,actual_start_date:actualStart,actual_end_date:actualEnd};void save(editing?{...base,id:editing.id,version:editing.version,user_id:editing.user_id}:selected.length>1?{...base,user_ids:selected}:{...base,user_id:selected[0]},editing||selected.length===1?"project_assignment.save":"project_assignment.batch")}}><div className="flex items-center justify-between"><h2 className="font-semibold">{editing?"투입 수정":`${selected.length}명 투입 설정`}</h2><Button type="button" variant="ghost" onClick={()=>setDialog(false)}>닫기</Button></div>
      <p className="text-xs text-muted-foreground">{selected.map(id=>names.get(id)).join(", ")}</p><label className="block text-xs">프로젝트 역할<Input autoFocus required value={role} onChange={e=>setRole(e.target.value)}/></label><div className="grid grid-cols-2 gap-3"><label className="text-xs">계획 시작일<Input type="date" required value={start} onChange={e=>setStart(e.target.value)}/></label><label className="text-xs">계획 종료일<Input type="date" required value={end} onChange={e=>setEnd(e.target.value)}/></label></div><div className="grid grid-cols-2 gap-3"><label className="text-xs">실제 시작일<Input type="date" value={actualStart} onChange={e=>setActualStart(e.target.value)}/></label><label className="text-xs">실제 종료일<Input type="date" value={actualEnd} onChange={e=>setActualEnd(e.target.value)}/></label></div><div className="grid grid-cols-2 gap-3"><label className="text-xs">투입률 (%)<Input type="number" min={0} max={100} step="0.01" required value={rate} onChange={e=>setRate(Number(e.target.value))}/></label><label className="text-xs">상태<select value={status} onChange={e=>setStatus(e.target.value)}>{assignmentStatuses.map(v=><option key={v} value={v}>{assignmentStatusLabels[v]}</option>)}</select></label></div><label className="block text-xs">메모<Input value={memo} onChange={e=>setMemo(e.target.value)}/></label>
      {validRange&&predicted>100&&<p role="alert" className="rounded-md border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">{start} ~ {end} 기간에 최고 투입률이 약 {predicted}%가 됩니다. 저장 시 모든 프로젝트를 다시 계산합니다.</p>}{message&&<p role="alert" className="text-xs text-destructive">{message}</p>}<Button disabled={busy} type="submit">{busy?"저장 중…":"투입 저장"}</Button>
    </form></div>}
  </>;
}
