"use client";
import {useState} from "react";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";
import {PlanningTimeline} from "@/components/planning-timeline";
import {allocationAt,allocationLabel} from "@/modules/project-resource/domain/metrics";
import type {projectAssignmentSchema,projectSchema} from "@/modules/project/infrastructure/repository";
import type {z} from "zod";
type Assignment=z.infer<typeof projectAssignmentSchema>;type Project=z.infer<typeof projectSchema>;
type Person={id:string;name:string;organization_id:string|null;position_id:string|null};
type Capacity={user_id:string;bucket_start:string;average_allocation:number;peak_allocation:number;minimum_availability:number};
export function ResourceDashboard({people,organizations,positions,projects,assignments,capacity,leave,today,start,end,granularity}:{people:Person[];organizations:{id:string;name:string}[];positions:{id:string;name:string}[];projects:Project[];assignments:Assignment[];capacity:Capacity[];leave:{user_id:string;start_date:string;end_date:string;leave_type:string}[];today:string;start:string;end:string;granularity:"month"|"week"}){
  const [view,setView]=useState<"board"|"timeline"|"table"|"heatmap">("board"),[query,setQuery]=useState(""),[org,setOrg]=useState(""),[periodStart,setPeriodStart]=useState(start),[periodEnd,setPeriodEnd]=useState(end);
  const filtered=people.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())&&(!org||p.organization_id===org));const names=new Map(projects.map(p=>[p.id,p.project_name]));const orgNames=new Map(organizations.map(o=>[o.id,o.name]));const positionNames=new Map(positions.map(p=>[p.id,p.name]));
  const buckets=[...new Set(capacity.map(row=>row.bucket_start))].sort();const amounts=new Map(capacity.map(row=>[`${row.user_id}:${row.bucket_start}`,row]));
  const personRows=filtered.map(person=>{const rows=assignments.filter(a=>a.user_id===person.id&&["PLANNED","CONFIRMED","IN_PROGRESS"].includes(a.status));const current=rows.filter(a=>a.planned_start_date<=today&&a.planned_end_date>=today);const upcoming=rows.filter(a=>a.planned_start_date>today).sort((a,b)=>a.planned_start_date.localeCompare(b.planned_start_date));const rate=allocationAt(rows,today);return {person,rows,current,next:upcoming[0],rate}});
  const tabs=[["board","리소스 보드"],["timeline","타임라인"],["table","테이블"],["heatmap","Capacity Heatmap"]] as const;
  return <><div className="mb-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["전체 직원",people.length],["투입 가능",personRows.filter(r=>r.rate<100).length],["높은 투입",personRows.filter(r=>r.rate>=80&&r.rate<=100).length],["과투입",personRows.filter(r=>r.rate>100).length]].map(([label,value])=><Card key={label} className="gap-0 py-4"><CardContent><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-xl font-bold">{value}</p></CardContent></Card>)}</div><Card className="mb-5"><CardContent className="flex flex-wrap items-end gap-3"><label className="text-xs">직원 검색<Input placeholder="이름" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="min-w-40 text-xs">조직<select value={org} onChange={e=>setOrg(e.target.value)}><option value="">전체 조직</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><form className="flex flex-wrap items-end gap-2" action="/admin/resources"><label className="text-xs">시작일<Input name="start" type="date" value={periodStart} onChange={e=>setPeriodStart(e.target.value)}/></label><label className="text-xs">종료일<Input name="end" type="date" value={periodEnd} onChange={e=>setPeriodEnd(e.target.value)}/></label><input type="hidden" name="granularity" value={granularity}/><Button type="submit" variant="outline">기간 조회</Button></form></CardContent></Card>
    <div className="mb-4 flex flex-wrap gap-2">{tabs.map(([key,label])=><Button key={key} size="sm" variant={view===key?"default":"outline"} onClick={()=>setView(key)}>{label}</Button>)}</div>
    {view==="board"&&<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{personRows.map(({person,current,rate})=><Card key={person.id} className="gap-3"><CardHeader><CardTitle>{person.name} <span className="text-xs font-normal text-muted-foreground">{orgNames.get(person.organization_id??"")??"미배정"} / {positionNames.get(person.position_id??"")??"—"}</span></CardTitle></CardHeader><CardContent className="text-xs"><div className="min-h-12 space-y-1">{current.map(row=><p key={row.id}>{names.get(row.project_id)??"프로젝트"} <strong>{row.allocation_rate}%</strong></p>)}{!current.length&&<p className="text-muted-foreground">현재 투입 없음</p>}</div><div className="mt-3 flex justify-between border-t pt-3"><span>총 투입률 <strong className={rate>100?"text-destructive":""}>{rate}%</strong></span><span>가용률 <strong>{Math.max(0,100-rate)}%</strong></span><Badge variant="outline" className={rate>100?"border-destructive text-destructive":""}>{allocationLabel(rate)}</Badge></div></CardContent></Card>)}</div>}
    {view==="timeline"&&<Card><CardHeader><CardTitle>전체 리소스 일정</CardTitle></CardHeader><CardContent><PlanningTimeline start={start} end={end} assignments={assignments} people={filtered} projects={projects} leave={leave}/></CardContent></Card>}
    {view==="table"&&<Card className="gap-0 py-0"><CardContent className="overflow-x-auto px-0"><Table><TableHeader><TableRow><TableHead className="pl-5">직원</TableHead><TableHead>조직</TableHead><TableHead>직급</TableHead><TableHead>현재 프로젝트</TableHead><TableHead>현재 투입률</TableHead><TableHead>다음 프로젝트</TableHead><TableHead>시작일</TableHead><TableHead>가용률</TableHead><TableHead>상태</TableHead></TableRow></TableHeader><TableBody>{personRows.map(({person,current,next,rate})=><TableRow key={person.id}><TableCell className="pl-5 font-semibold">{person.name}</TableCell><TableCell>{orgNames.get(person.organization_id??"")??"—"}</TableCell><TableCell>{positionNames.get(person.position_id??"")??"—"}</TableCell><TableCell>{current.map(row=>names.get(row.project_id)).join(", ")||"대기"}</TableCell><TableCell>{rate}%</TableCell><TableCell>{next?names.get(next.project_id):"—"}</TableCell><TableCell>{next?.planned_start_date??"—"}</TableCell><TableCell>{Math.max(0,100-rate)}%</TableCell><TableCell><Badge variant="outline" className={rate>100?"border-destructive text-destructive":""}>{allocationLabel(rate)}</Badge></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>}
    {view==="heatmap"&&<Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle>직원별 Capacity Heatmap</CardTitle><div className="flex gap-2"><a href={`/admin/resources?start=${start}&end=${end}&granularity=month`} className={`rounded-md border px-3 py-1 text-xs ${granularity==="month"?"bg-primary text-white":""}`}>월</a><a href={`/admin/resources?start=${start}&end=${end}&granularity=week`} className={`rounded-md border px-3 py-1 text-xs ${granularity==="week"?"bg-primary text-white":""}`}>주</a></div></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-max border-collapse text-xs"><thead><tr><th className="sticky left-0 bg-card p-2 text-left">직원</th>{buckets.map(bucket=><th className="p-2 font-medium" key={bucket}>{bucket}</th>)}</tr></thead><tbody>{filtered.map(person=><tr key={person.id} className="border-t"><th className="sticky left-0 bg-card p-2 text-left">{person.name}</th>{buckets.map(bucket=>{const rate=amounts.get(`${person.id}:${bucket}`)?.peak_allocation??0;return <td key={bucket} className="p-1 text-center"><span title={`최고 ${rate}% · 평균 ${amounts.get(`${person.id}:${bucket}`)?.average_allocation??0}%`} className={`block rounded px-2 py-2 ${rate>100?"bg-red-100 font-semibold text-destructive":rate>=80?"bg-blue-200":rate>=50?"bg-blue-100":"bg-muted text-muted-foreground"}`}>{rate}%</span></td>})}</tr>)}</tbody></table><p className="mt-3 text-[11px] text-muted-foreground">셀은 기간 내 최고 투입률입니다. 100% 초과는 과투입, 100% 미만은 여유가 있습니다.</p></CardContent></Card>}
  </>;
}
