"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {workCategoryLabels} from "@/modules/work-management/domain/contracts";
import {shiftDays} from "@/modules/work-management/domain/week";
import type {weeklyReportSchema,rosterSchema} from "@/modules/work-management/infrastructure/repository";
import type {z} from "zod";
type Report=z.infer<typeof weeklyReportSchema>;type Person=z.infer<typeof rosterSchema>;
export function WeeklyPresentation({week,roster,reports,organizations}:{week:string;roster:Person[];reports:Report[];organizations:{id:string;name:string}[]}){
 const [organization,setOrganization]=useState("");const [index,setIndex]=useState(0);const people=useMemo(()=>roster.filter(person=>!organization||person.organization_id===organization),[organization,roster]);const person=people[Math.min(index,people.length-1)];const report=reports.find(item=>item.user_id===person?.user_id);const orgName=organizations.find(item=>item.id===person?.organization_id)?.name??"조직 미지정";
 useEffect(()=>{function onKey(event:KeyboardEvent){if(event.key==="ArrowRight"||event.key==="PageDown")setIndex(current=>Math.min(current+1,people.length-1));if(event.key==="ArrowLeft"||event.key==="PageUp")setIndex(current=>Math.max(current-1,0))}window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[people.length]);
 const groups=new Map<string,Report["entries_snapshot"]>();for(const entry of report?.entries_snapshot??[]){const name=entry.project_name??workCategoryLabels[entry.category as keyof typeof workCategoryLabels]??entry.category;groups.set(name,[...(groups.get(name)??[]),entry])}
 return <main className="min-h-screen bg-[#f6f8fb] px-5 py-6 text-brand-navy md:px-10"><div className="mx-auto max-w-[1200px]"><div className="mb-5 flex flex-wrap items-center justify-between gap-4 text-sm"><Link href={`/weekly-reports?week=${week}`} className="rounded-md border bg-white px-4 py-2">← 주간보고로</Link><div className="flex flex-wrap items-center gap-2"><Link className="rounded-md border bg-white px-3 py-2" href={`?week=${shiftDays(week,-7)}`}>이전 주</Link><Link className="rounded-md border bg-white px-3 py-2" href={`?week=${shiftDays(week,7)}`}>다음 주</Link><select aria-label="조직 필터" value={organization} onChange={event=>{setOrganization(event.target.value);setIndex(0)}} className="rounded-md border bg-white px-3 py-2"><option value="">전체 조직</option>{organizations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="보고 직원" value={person?.user_id??""} onChange={event=>setIndex(people.findIndex(item=>item.user_id===event.target.value))} className="rounded-md border bg-white px-3 py-2">{people.map(item=><option key={item.user_id} value={item.user_id}>{item.name}</option>)}</select></div></div>
 <article className="min-h-[72vh] rounded-lg border bg-white px-8 py-8 shadow-sm md:px-14 md:py-12"><div className="mb-9 border-b pb-7"><p className="text-sm font-semibold tracking-widest text-primary">DIGITAL SQUARE · WEEKLY REPORT</p><h1 className="mt-3 text-3xl font-bold md:text-4xl">주간 업무보고</h1><p className="mt-2 text-base text-muted-foreground">{week} ~ {shiftDays(week,4)}</p><div className="mt-7 flex items-end justify-between"><div><p className="text-sm text-muted-foreground">{orgName}</p><h2 className="mt-1 text-2xl font-bold">{person?.name??"보고 대상 없음"}</h2></div><span className="rounded-full border px-3 py-1 text-sm">{report?.status==="CONFIRMED"?"확정본":report?"초안":"미작성"}</span></div></div>
 {report?<div className="grid gap-10 lg:grid-cols-[1.4fr_1fr]"><div><h3 className="mb-4 text-xl font-bold">이번 주 주요 업무</h3>{report.summary&&<p className="mb-6 whitespace-pre-wrap text-base leading-7">{report.summary}</p>}{[...groups].map(([group,entries],i)=><section key={group} className="mb-5"><h4 className="mb-2 text-lg font-semibold">{i+1}. {group}</h4><ul className="space-y-1.5 pl-5 text-base leading-7">{entries.map(entry=><li key={entry.id} className="list-disc">{entry.title}</li>)}</ul></section>)}{!groups.size&&<p className="text-muted-foreground">업무일지 스냅샷이 없습니다.</p>}</div><div className="space-y-7"><section><h3 className="mb-2 text-lg font-bold">완료 업무</h3><p className="whitespace-pre-wrap text-base leading-7">{report.completed_work||"—"}</p></section><section><h3 className="mb-2 text-lg font-bold">진행 중 업무</h3><p className="whitespace-pre-wrap text-base leading-7">{report.in_progress_work||"—"}</p></section><section><h3 className="mb-2 text-lg font-bold">주요 Issue</h3><p className="whitespace-pre-wrap text-base leading-7">{report.issues||"—"}</p></section><section><h3 className="mb-2 text-lg font-bold">다음 주 계획</h3><p className="whitespace-pre-wrap text-base leading-7">{report.next_week_plan||"—"}</p></section></div></div>:<p className="py-20 text-center text-lg text-muted-foreground">등록된 보고가 없습니다.</p>}</article><div className="mt-5 flex items-center justify-between"><button disabled={index<=0} onClick={()=>setIndex(i=>i-1)} className="rounded-md border bg-white px-5 py-2 disabled:opacity-40">← 이전 직원</button><span className="text-sm text-muted-foreground">{people.length?index+1:0} / {people.length}</span><button disabled={index>=people.length-1} onClick={()=>setIndex(i=>i+1)} className="rounded-md border bg-white px-5 py-2 disabled:opacity-40">다음 직원 →</button></div></div></main>
}
