"use client";
import {useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Button} from "@/components/ui/button";
import {Badge} from "@/components/ui/badge";
import {shiftDays} from "@/modules/work-management/domain/week";
import type {weeklyReportSchema,rosterSchema} from "@/modules/work-management/infrastructure/repository";
import type {z} from "zod";
type Report=z.infer<typeof weeklyReportSchema>;type Person=z.infer<typeof rosterSchema>;
export function WeeklyReportClient({week,roster,reports,organizations,accountId,canWrite,canReadTeam}:{week:string;roster:Person[];reports:Report[];organizations:{id:string;name:string}[];accountId:string;canWrite:boolean;canReadTeam:boolean}){
 const router=useRouter();const [organization,setOrganization]=useState(""),[selected,setSelected]=useState(accountId),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [draft,setDraft]=useState<Partial<Pick<Report,"summary"|"completed_work"|"in_progress_work"|"issues"|"next_week_plan">>>({});
 const report=reports.find(r=>r.user_id===selected);const own=selected===accountId;const end=shiftDays(week,4);
 const filtered=roster.filter(row=>!organization||row.organization_id===organization);const count={total:filtered.length,confirmed:filtered.filter(r=>r.status==="CONFIRMED").length,draft:filtered.filter(r=>r.status==="DRAFT").length,missing:filtered.filter(r=>!r.status&&r.approved_leave_days<5).length};
 const names=new Map(organizations.map(o=>[o.id,o.name]));
 const fields=[["summary","요약"],["completed_work","완료 업무"],["in_progress_work","진행 중 업무"],["issues","이슈"],["next_week_plan","다음 주 계획"]] as const;
 async function command(action:string,payload:Record<string,unknown>){setBusy(true);setMessage("");try{const response=await fetch("/api/work-management",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,payload})});const body=await response.json();if(!response.ok)throw new Error(body.error?.message??"처리하지 못했습니다.");setMessage(body.data?.message??"저장했습니다.");setDraft({});router.refresh()}catch(error){setMessage(error instanceof Error?error.message:"연결을 확인해 주세요.")}finally{setBusy(false)}}
 return <><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs text-muted-foreground">월요일 ~ 금요일</p><h2 className="mt-1 text-lg font-bold">{week} ~ {end}</h2></div><div className="flex flex-wrap gap-2"><Link className="rounded-md border bg-card px-3 py-2 text-xs" href={`/weekly-reports?week=${shiftDays(week,-7)}`}>← 이전 주</Link><Link className="rounded-md border bg-card px-3 py-2 text-xs" href={`/weekly-reports?week=${shiftDays(week,7)}`}>다음 주 →</Link>{canReadTeam&&<Link className="rounded-md bg-primary px-3 py-2 text-xs text-white" href={`/presentation/weekly-reports?week=${week}`}>보고 모드</Link>}</div></div>
 <div className="mb-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["보고 대상",count.total],["작성 완료",count.confirmed],["작성 중",count.draft],["미작성",count.missing]].map(([label,value])=><Card key={label}><CardContent><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-xl font-bold">{value}</p></CardContent></Card>)}</div>
 <div className="grid gap-5 xl:grid-cols-[320px_1fr]"><Card><CardHeader><CardTitle>직원별 현황</CardTitle></CardHeader><CardContent><select aria-label="조직 필터" value={organization} onChange={e=>setOrganization(e.target.value)}><option value="">전체 조직</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select><div className="mt-3 max-h-[620px] space-y-1 overflow-y-auto">{filtered.map(row=><button key={row.user_id} onClick={()=>{setSelected(row.user_id);setDraft({});setMessage("")}} className={`flex w-full items-center justify-between rounded-md border px-3 py-2 text-left text-xs ${selected===row.user_id?"border-primary bg-brand-soft":"bg-card"}`}><span>{row.name}<small className="ml-2 text-muted-foreground">{names.get(row.organization_id??"")??""}</small></span><Badge variant="outline">{row.status==="CONFIRMED"?"확정":row.status==="DRAFT"?"작성 중":row.approved_leave_days>=5?"승인 휴가":"미작성"}</Badge></button>)}</div></CardContent></Card>
 <Card><CardHeader><CardTitle>{roster.find(r=>r.user_id===selected)?.name??"주간보고"} · {report?.status==="CONFIRMED"?"확정본":report?"초안":"미작성"}</CardTitle></CardHeader><CardContent>{own&&canWrite&&!report&&<Button disabled={busy} onClick={()=>void command("weekly_report.generate",{week_start_date:week})}>업무일지에서 초안 만들기</Button>}{report&&<><p className="mb-4 text-xs text-muted-foreground">기록 스냅샷 {report.snapshot_taken_at.slice(0,16).replace("T"," ")} · 업무 {report.entries_snapshot.length}건</p><div className="mb-5 space-y-2 rounded-md border bg-muted/50 p-3 text-xs">{report.entries_snapshot.map(entry=><p key={entry.id}><span className="text-muted-foreground">{entry.date} · {entry.project_name??entry.category}</span> · {entry.title} <span className="text-muted-foreground">({entry.minutes}분)</span></p>)}{!report.entries_snapshot.length&&<p className="text-muted-foreground">해당 주의 업무일지가 없습니다. 프로젝트 배정 여부와 관계없이 주간보고를 작성할 수 있습니다.</p>}</div><div className="space-y-4">{fields.map(([key,label])=><label key={key} className="block text-xs font-semibold">{label}<textarea className="mt-1 min-h-24 w-full rounded-md border bg-card p-3 text-sm font-normal" value={draft[key]??report[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})} readOnly={!own||report.status==="CONFIRMED"}/></label>)}</div>{own&&canWrite&&report.status==="DRAFT"&&<div className="mt-4 flex flex-wrap gap-2"><Button disabled={busy} onClick={()=>void command("weekly_report.save",{week_start_date:week,version:report.version,...Object.fromEntries(fields.map(([key])=>[key,draft[key]??report[key]]))})}>내용 저장</Button><Button variant="outline" disabled={busy} onClick={()=>void command("weekly_report.refresh",{week_start_date:week,version:report.version})}>업무일지 다시 불러오기</Button><Button variant="outline" disabled={busy||Object.keys(draft).length>0} title={Object.keys(draft).length>0?"수정 내용을 먼저 저장해 주세요.":undefined} onClick={()=>{if(confirm("현재 내용을 확정하면 이후 업무일지 변경이 반영되지 않습니다. 확정하시겠습니까?"))void command("weekly_report.confirm",{week_start_date:week,version:report.version})}}>보고 확정</Button></div>}{report.status==="CONFIRMED"&&<p className="mt-4 text-xs text-muted-foreground">확정 후의 업무일지 변경은 이 보고 내용에 반영되지 않습니다.</p>}</>}{!report&&!own&&<p className="py-12 text-center text-xs text-muted-foreground">작성된 보고가 없습니다.</p>}{message&&<p role="status" className="mt-4 text-xs text-primary">{message}</p>}</CardContent></Card></div></>;
}
