"use client";
import {useState} from "react";
import Link from "next/link";
import {CommandForm,type Field} from "@/components/command-form";
import {Button} from "@/components/ui/button";
import {Badge} from "@/components/ui/badge";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {careerLabel,careerMonths,skillLevelLabels,skillLevels} from "@/modules/workforce-profile/domain/contracts";
import type {workforceProfile,skillCatalog} from "@/modules/workforce-profile/infrastructure/repository";
import type {Employee} from "@/modules/users/domain/contracts";

type Data=Awaited<ReturnType<typeof workforceProfile>>;type Skill=Awaited<ReturnType<typeof skillCatalog>>[number];
const endpoint="/api/workforce-profile";
const levelOptions=skillLevels.map(value=>({value,label:skillLevelLabels[value]}));
export function WorkforceProfileView({employee,data,skills,organization,position,today,canWrite,canManage,canExport}:{employee:Employee;data:Data;skills:Skill[];organization:string;position:string;today:string;canWrite:boolean;canManage:boolean;canExport:boolean}){
 const [editing,setEditing]=useState<string|null>(null),[exportBirth,setExportBirth]=useState(false),[exportError,setExportError]=useState("");
 const career=careerLabel(careerMonths(data.profile?.career_start_date??null,data.profile?.career_months_override??null,today));
 const skillMap=new Map(skills.map(s=>[s.id,s]));
 async function exportExcel(){setExportError("");try{const response=await fetch("/api/workforce-profile/export",{method:"POST",headers:{"Content-Type":"application/json","X-Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({user_ids:[employee.id],include_birth_date:exportBirth})});if(!response.ok){const body=await response.json();throw new Error(body.error?.message??"생성하지 못했습니다.")}const blob=await response.blob(),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download=`DigitalSquare_WorkforceProfile_${employee.name}.xlsx`;anchor.click();URL.revokeObjectURL(url)}catch(error){setExportError(error instanceof Error?error.message:"생성하지 못했습니다.")}}
 const form=(action:string,constants:Record<string,unknown>,fields:Field[],key:string)=> <CommandForm key={key} endpoint={endpoint} action={action} constants={constants} fields={fields} submit="저장"/>;
 return <div className="space-y-5">
  <Card><CardHeader><CardTitle className="flex flex-wrap items-center justify-between gap-3"><span>{employee.name} · 인력프로필</span><Badge variant="outline">{data.profile?.profile_status??"DRAFT"}</Badge></CardTitle></CardHeader><CardContent>
   <dl className="grid gap-4 text-sm sm:grid-cols-4">{[["소속",organization],["직급",position],["업무경력",career],["이메일",employee.email]].map(([label,value])=><div key={label}><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1">{value||"—"}</dd></div>)}</dl>
   {canExport&&<div className="mt-5 flex flex-wrap items-center gap-3 border-t pt-4"><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={exportBirth} onChange={e=>setExportBirth(e.target.checked)}/>생년월일 포함</label><Button type="button" size="sm" variant="outline" onClick={exportExcel}>인력프로필 Excel</Button>{exportError&&<span className="text-xs text-destructive" role="alert">{exportError}</span>}</div>}
  </CardContent></Card>
   {canWrite&&<Card><CardHeader><CardTitle>전문 경력 기본정보</CardTitle></CardHeader><CardContent>{form("profile.save",{user_id:employee.id,...data.profile?{version:data.profile.version}:{}},[
   {name:"career_start_date",label:"업무경력 기준일",type:"date",value:data.profile?.career_start_date??""},
   {name:"profile_status",label:"프로필 상태",type:"select",value:data.profile?.profile_status??"DRAFT",options:[{value:"DRAFT",label:"작성 중"},{value:"READY",label:"제출 준비"}]},
   {name:"summary",label:"소개 / 요약",type:"textarea",value:data.profile?.summary??""},
   ...canManage?[{name:"birth_date",label:"생년월일 (제한 정보)",type:"date",value:data.profile?.birth_date??""},{name:"career_months_override",label:"경력 개월수 보정 (기존 Excel 이관용)",value:data.profile?.career_months_override??""},{name:"career_override_reason",label:"보정 사유",value:data.profile?.career_override_reason??""}] as Field[]:[],
  ],`profile-${data.profile?.version??0}`)}</CardContent></Card>}
  <div className="grid gap-5 xl:grid-cols-2">
   <Card><CardHeader><CardTitle>학력</CardTitle></CardHeader><CardContent className="space-y-3">{data.educations.map(x=><div className="rounded border p-3 text-sm" key={x.id}><div className="flex justify-between gap-3"><span>{x.school_name} · {x.major||"전공 미등록"} {x.highest_education&&<Badge variant="outline">최종학력</Badge>}</span>{canWrite&&<Button size="sm" variant="ghost" onClick={()=>setEditing(x.id)}>수정</Button>}</div>{editing===x.id&&educationForm(x)}</div>)}{!data.educations.length&&<p className="text-xs text-muted-foreground">등록된 학력이 없습니다.</p>}{canWrite&&<details className="border-t pt-3"><summary className="cursor-pointer text-sm font-medium">학력 추가</summary><div className="mt-3">{educationForm(null)}</div></details>}</CardContent></Card>
   <Card><CardHeader><CardTitle>보유 기술</CardTitle></CardHeader><CardContent className="space-y-3">{data.employeeSkills.map(x=><div className="flex items-center justify-between gap-2 rounded border p-3 text-sm" key={x.id}><span>{skillMap.get(x.skill_id)?.name??"기술"} {x.level&&<Badge variant="outline">{skillLevelLabels[x.level as keyof typeof skillLevelLabels]??x.level}</Badge>}</span>{canWrite&&<Button size="sm" variant="ghost" onClick={()=>setEditing(x.id)}>수정</Button>}{editing===x.id&&skillForm(x)}</div>)}{!data.employeeSkills.length&&<p className="text-xs text-muted-foreground">등록된 기술이 없습니다.</p>}{canWrite&&<details className="border-t pt-3"><summary className="cursor-pointer text-sm font-medium">기술 추가</summary><div className="mt-3">{skillForm(null)}</div></details>}</CardContent></Card>
   <Card><CardHeader><CardTitle>자격 / Certification</CardTitle></CardHeader><CardContent className="space-y-3">{data.certifications.map(x=><div className="rounded border p-3 text-sm" key={x.id}><div className="flex justify-between"><span>{x.certification_name} · {x.issuer}</span>{canWrite&&<Button size="sm" variant="ghost" onClick={()=>setEditing(x.id)}>수정</Button>}</div>{editing===x.id&&certForm(x)}</div>)}{!data.certifications.length&&<p className="text-xs text-muted-foreground">등록된 자격이 없습니다.</p>}{canWrite&&<details className="border-t pt-3"><summary className="cursor-pointer text-sm font-medium">자격 추가</summary><div className="mt-3">{certForm(null)}</div></details>}</CardContent></Card>
   <Card><CardHeader><CardTitle>현재 / 예정 프로젝트</CardTitle></CardHeader><CardContent className="space-y-2 text-sm">{data.assignments.filter(a=>a.planned_end_date>=today&&a.status!=="CANCELED").map(a=><div key={a.id} className="rounded border p-3"><Link className="font-medium text-primary hover:underline" href={`/admin/projects/${a.project_id}`}>{a.project_name}</Link><p className="text-xs text-muted-foreground">{a.project_role} · {a.planned_start_date} ~ {a.planned_end_date} · {a.allocation_rate}%</p></div>)}{!data.assignments.some(a=>a.planned_end_date>=today&&a.status!=="CANCELED")&&"현재 또는 예정된 프로젝트가 없습니다."}</CardContent></Card>
  </div>
  <Card><CardHeader><CardTitle>프로젝트 수행경력</CardTitle></CardHeader><CardContent className="space-y-3">{data.experiences.map(x=><div key={x.id} className="rounded border p-4 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><div><Badge variant="outline">{x.source_type==="INTERNAL_PROJECT"?"ERP 프로젝트":"과거 경력"}</Badge> <strong>{x.display_name}</strong><p className="mt-1 text-xs text-muted-foreground">{x.display_start??"—"} ~ {x.display_end??"현재"} · {x.display_role}</p></div>{canWrite&&<Button size="sm" variant="ghost" onClick={()=>setEditing(x.id)}>수정</Button>}</div><p className="mt-2 whitespace-pre-wrap">{x.responsibilities}</p>{x.technologies&&<p className="mt-1 text-xs text-muted-foreground">기술: {x.technologies}</p>}{editing===x.id&&<div className="mt-3 border-t pt-3">{experienceForm(x)}</div>}</div>)}{!data.experiences.length&&<p className="text-xs text-muted-foreground">확인된 프로젝트 경력이 없습니다.</p>}{canWrite&&<div className="grid gap-4 border-t pt-4 xl:grid-cols-2"><details><summary className="cursor-pointer text-sm font-medium">과거 프로젝트 경력 추가</summary><div className="mt-3">{experienceForm(null)}</div></details><details><summary className="cursor-pointer text-sm font-medium">ERP 프로젝트 경력 반영</summary><div className="mt-3">{experienceForm("internal")}</div></details></div>}</CardContent></Card>
 </div>;
 function educationForm(x:Data["educations"][number]|null){return form("education.save",{user_id:employee.id,...x?{id:x.id,version:x.version}:{}},[{name:"school_name",label:"학교",value:x?.school_name,required:true},{name:"degree",label:"학위",value:x?.degree??""},{name:"major",label:"전공",value:x?.major??""},{name:"start_date",label:"시작일",type:"date",value:x?.start_date??""},{name:"end_date",label:"종료일",type:"date",value:x?.end_date??""},{name:"graduation_status",label:"상태",type:"select",value:x?.graduation_status??"GRADUATED",options:[{value:"ENROLLED",label:"재학"},{value:"GRADUATED",label:"졸업"},{value:"COMPLETED",label:"수료"},{value:"WITHDRAWN",label:"중단"}]},{name:"highest_education",label:"최종학력",type:"checkbox",value:x?.highest_education??false},{name:"active",label:"표시",type:"checkbox",value:x?.active??true}],`edu-${x?.id??"new"}-${x?.version??0}`)}
 function skillForm(x:Data["employeeSkills"][number]|null){return form("employee_skill.save",{user_id:employee.id,...x?{id:x.id,version:x.version}:{}},[{name:"skill_id",label:"기술",type:"select",value:x?.skill_id??"",options:skills.map(s=>({value:s.id,label:s.name})),required:true},{name:"level",label:"수준",type:"select",value:x?.level??"",options:levelOptions},{name:"years_experience",label:"경험 연수",value:x?.years_experience??""},{name:"last_used_date",label:"최근 사용일",type:"date",value:x?.last_used_date??""},{name:"memo",label:"메모",value:x?.memo??""},{name:"active",label:"표시",type:"checkbox",value:x?.active??true}],`skill-${x?.id??"new"}-${x?.version??0}`)}
 function certForm(x:Data["certifications"][number]|null){return form("certification.save",{user_id:employee.id,...x?{id:x.id,version:x.version}:{}},[{name:"certification_name",label:"자격명",value:x?.certification_name,required:true},{name:"issuer",label:"발급기관",value:x?.issuer??""},{name:"obtained_date",label:"취득일",type:"date",value:x?.obtained_date??""},{name:"expiry_date",label:"만료일",type:"date",value:x?.expiry_date??""},{name:"credential_id",label:"증명번호",value:x?.credential_id??""},{name:"active",label:"표시",type:"checkbox",value:x?.active??true}],`cert-${x?.id??"new"}-${x?.version??0}`)}
 function experienceForm(x:Data["experiences"][number]|"internal"|null){const row=typeof x==="object"?x:null,internal=x==="internal"||row?.source_type==="INTERNAL_PROJECT";return form("experience.save",{user_id:employee.id,source_type:internal?"INTERNAL_PROJECT":"MANUAL_HISTORY",...row?{id:row.id,version:row.version}:{}},[
  ...internal?[{name:"project_assignment_id",label:"기존 프로젝트 투입",type:"select",required:true,value:row?.project_assignment_id??"",options:data.assignments.map(a=>({value:a.id,label:`${a.project_name} · ${a.project_role} · ${a.planned_start_date}`}))}] as Field[]:[{name:"project_name",label:"프로젝트명",value:row?.project_name??"",required:true},{name:"customer_name",label:"고객사",value:row?.customer_name??""},{name:"category",label:"구분",value:row?.category??""},{name:"start_date",label:"참여 시작일",type:"date",value:row?.start_date??"",required:true},{name:"end_date",label:"참여 종료일",type:"date",value:row?.end_date??""},{name:"role",label:"역할",value:row?.role??"",required:true}] as Field[],
  {name:"responsibilities",label:"프로젝트 주요 업무",type:"textarea",value:row?.responsibilities??"",required:true,minLength:2},{name:"technologies",label:"사용 기술",value:row?.technologies??""},{name:"active",label:"프로필에 표시",type:"checkbox",value:row?.active??true},
 ],`exp-${row?.id??(internal?"internal":"manual")}-${row?.version??0}`)}
}
