import "server-only";
import {z} from "zod";
import {serverClient} from "@/shared/infrastructure/supabase/server";
import {databaseError} from "@/shared/domain/errors";
import type {CorporateCardRepository} from "../application/commands";
export const cardSchema=z.object({id:z.uuid(),card_name:z.string(),card_company:z.string(),identifier:z.string(),last_four:z.string(),status:z.string(),memo:z.string(),version:z.number(),created_at:z.string(),updated_at:z.string()});
export const cardAssignmentSchema=z.object({id:z.uuid(),corporate_card_id:z.uuid(),project_id:z.uuid(),responsible_user_id:z.uuid(),assigned_from:z.string(),assigned_to:z.string().nullable(),status:z.string(),memo:z.string(),version:z.number(),created_at:z.string(),updated_at:z.string()});
export const expenseSchema=z.object({id:z.uuid(),transaction_date:z.string(),project_id:z.uuid(),corporate_card_id:z.uuid(),user_id:z.uuid(),merchant:z.string(),purpose:z.string(),category:z.string(),supply_amount:z.number(),vat_amount:z.number(),total_amount:z.number(),memo:z.string(),receipt_key:z.string().nullable(),settlement_status:z.string(),deleted_at:z.string().nullable(),version:z.number(),created_at:z.string(),updated_at:z.string()});
export const settlementEntrySchema=z.object({id:z.uuid(),transaction_date:z.string(),project_code:z.string(),project_name:z.string(),card:z.string(),user_name:z.string(),merchant:z.string(),purpose:z.string(),category:z.string(),supply_amount:z.number(),vat_amount:z.number(),total_amount:z.number(),memo:z.string()});
export const settlementSchema=z.object({id:z.uuid(),settlement_month:z.string(),status:z.string(),total_count:z.number(),total_supply_amount:z.number(),total_vat_amount:z.number(),total_amount:z.number(),entries_snapshot:z.array(settlementEntrySchema),file_key:z.string().nullable(),checksum:z.string().nullable(),generated_at:z.string(),generated_by:z.uuid().nullable(),sent_at:z.string().nullable(),send_generation:z.number(),version:z.number(),created_at:z.string(),updated_at:z.string()});
export function corporateCardRepository():CorporateCardRepository{return {async execute(command,requestId){const client=await serverClient();const {data,error}=await client.rpc("corporate_card_command",{p_action:command.action,p_payload:command.payload,p_request_id:requestId});if(error)throw databaseError(error);return data}}}
export async function cardCatalog(){const client=await serverClient();const [cards,assignments]=await Promise.all([client.from("corporate_cards").select("*").order("card_name").limit(1000),client.from("project_card_assignments").select("*").order("assigned_from",{ascending:false}).limit(1000)]);if(cards.error)throw databaseError(cards.error);if(assignments.error)throw databaseError(assignments.error);return {cards:cardSchema.array().parse(cards.data),assignments:cardAssignmentSchema.array().parse(assignments.data)}}
export async function projectExpenses(projectId:string){const client=await serverClient();const {data,error}=await client.from("expenses").select("*").eq("project_id",projectId).is("deleted_at",null).order("transaction_date",{ascending:false}).limit(500);if(error)throw databaseError(error);return expenseSchema.array().parse(data)}
export async function projectExpenseSummary(projectId:string,month:string){const client=await serverClient();const {data,error}=await client.rpc("project_expense_summary",{p_project_id:projectId,p_month:month});if(error)throw databaseError(error);return z.object({month_amount:z.number(),project_amount:z.number(),by_category:z.record(z.string(),z.number()),by_user:z.record(z.string(),z.number()),by_card:z.record(z.string(),z.number())}).parse(data)}
export async function settlements(){const client=await serverClient();const {data,error}=await client.from("monthly_card_reports").select("*").order("settlement_month",{ascending:false}).limit(120);if(error)throw databaseError(error);return settlementSchema.array().parse(data)}
export async function settlement(month:string){const client=await serverClient();const {data,error}=await client.from("monthly_card_reports").select("*").eq("settlement_month",month).maybeSingle();if(error)throw databaseError(error);return data?settlementSchema.parse(data):null}
export const deliverySchema=z.object({id:z.uuid(),recipient_email:z.string(),status:z.string(),attempt_count:z.number(),last_error_code:z.string().nullable(),created_at:z.string(),updated_at:z.string(),recent_attempt:z.object({attempt:z.number(),status:z.string(),error_code:z.string().nullable(),attempted_at:z.string()}).nullable()});
export async function settlementDelivery(reportId:string){const client=await serverClient();const {data,error}=await client.rpc("card_settlement_delivery",{p_report_id:reportId});if(error)throw databaseError(error);return deliverySchema.array().parse(data)}
export const settingSchema=z.object({value:z.object({enabled:z.boolean(),recipients:z.array(z.string()),cc:z.array(z.string()),send_day:z.number(),send_time:z.string(),timezone:z.string(),subject_template:z.string()}),version:z.number(),updated_at:z.string()});
export async function settlementSetting(){const client=await serverClient();const {data,error}=await client.rpc("card_settlement_setting");if(error)throw databaseError(error);return settingSchema.parse(data)}
export async function cardMonthAmount(month:string){const client=await serverClient();const {data,error}=await client.rpc("card_month_amount",{p_month:month});if(error)throw databaseError(error);return z.number().parse(data)}
