import {NextResponse} from "next/server";
import {z} from "zod";
import {currentAccount} from "@/shared/auth/account";
import {authorize} from "@/modules/rbac/domain/policy";
import {serverClient} from "@/shared/infrastructure/supabase/server";
import {databaseError} from "@/shared/domain/errors";
import {failure,readMutation} from "@/shared/infrastructure/http";
import {settlementSchema} from "@/modules/corporate-card/infrastructure/repository";
import {downloadSettlementExcel,storeSettlementExcel} from "@/modules/corporate-card/infrastructure/private-storage";
const inputSchema=z.object({settlement_month:z.iso.date(),version:z.number().int().positive()});
export async function POST(request:Request){const requestId=crypto.randomUUID();try{authorize(await currentAccount(),"CARD_SETTLEMENT_MANAGE");const input=inputSchema.parse(await readMutation(request));const client=await serverClient();const result=await client.from("monthly_card_reports").select("*").eq("settlement_month",input.settlement_month).single();if(result.error)throw databaseError(result.error);const report=settlementSchema.parse(result.data);if(report.version!==input.version||!["DRAFT","REVIEW"].includes(report.status))throw new Error("정산 상태가 변경되었습니다. 새로고침 후 다시 시도하세요.");const file=await storeSettlementExcel(report);const saved=await client.rpc("corporate_card_command",{p_action:"settlement.file",p_payload:{settlement_month:report.settlement_month,version:report.version,file_key:file.fileKey,checksum:file.checksum},p_request_id:requestId});if(saved.error)throw databaseError(saved.error);return NextResponse.json({data:{message:"Excel 파일을 생성했습니다.",checksum:file.checksum}},{headers:{"Cache-Control":"no-store"}})}catch(error){return failure(error,requestId)}}
export async function GET(request:Request){const requestId=crypto.randomUUID();try{authorize(await currentAccount(),"CARD_SETTLEMENT_READ");const month=z.iso.date().parse(new URL(request.url).searchParams.get("month"));const client=await serverClient();const result=await client.from("monthly_card_reports").select("*").eq("settlement_month",month).single();if(result.error)throw databaseError(result.error);const report=settlementSchema.parse(result.data);if(!report.file_key)throw new Error("Excel 파일이 없습니다.");const content=await downloadSettlementExcel(report.file_key);return new NextResponse(new Uint8Array(content),{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":`attachment; filename="DigitalSquare_CorporateCard_${month.slice(0,7)}.xlsx"`,"Cache-Control":"private, no-store"}})}catch(error){return failure(error,requestId)}}
